import { Router } from 'express';
import { randomUUID } from 'node:crypto';

import { type AuthenticatedRequest, requireAuth, requirePermission } from '../auth.js';
import { evaluateAnalyticsFormula } from '../analyticsFormula.js';
import { buildAnalyticsDataset, type AnalyticsFilters } from '../analyticsService.js';
import { requireEntitlement, requireOperationalLicense } from '../middleware/entitlements.js';
import { str } from '../requestUtils.js';
import { supabaseAdmin } from '../supabaseClients.js';
import { getEntitlement } from '../entitlementService.js';
import { OllamaProvider } from '../ai/ollamaProvider.js';
import { runtimeConfig } from '../config/runtime.js';

const widgetTypes = new Set(['kpi','line','bar','stacked-bar','donut','table','heatmap','map','insight']);
const baseVariables = { emissions_total: 0, scope1_total: 0, scope2_total: 0, production_total: 0, scope2_quantity: 0, renewable_quantity: 0, activity_count: 0, activities_with_evidence: 0, approved_activity_count: 0, facility_count: 0, project_count: 0, planned_reduction: 0 };
const defaultWidgets = [
  { id: 'virtual-total', title: 'Total emissions', widget_type: 'kpi', kpi_key: 'emissions_total', dimension: '', grid_w: 3, grid_h: 2, position: 0, configuration: {} },
  { id: 'virtual-scope1', title: 'Scope 1', widget_type: 'kpi', kpi_key: 'scope1_total', dimension: '', grid_w: 3, grid_h: 2, position: 1, configuration: {} },
  { id: 'virtual-scope2', title: 'Scope 2', widget_type: 'kpi', kpi_key: 'scope2_total', dimension: '', grid_w: 3, grid_h: 2, position: 2, configuration: {} },
  { id: 'virtual-intensity', title: 'Carbon intensity', widget_type: 'kpi', kpi_key: 'carbon_intensity', dimension: '', grid_w: 3, grid_h: 2, position: 3, configuration: {} },
  { id: 'virtual-trend', title: 'Monthly emissions trend', widget_type: 'line', kpi_key: 'emissions_total', dimension: 'month', grid_w: 8, grid_h: 4, position: 4, configuration: {} },
  { id: 'virtual-source', title: 'Emission sources', widget_type: 'bar', kpi_key: 'emissions_total', dimension: 'source', grid_w: 4, grid_h: 4, position: 5, configuration: {} },
  { id: 'virtual-facility', title: 'Facility performance', widget_type: 'table', kpi_key: 'carbon_intensity', dimension: 'facility', grid_w: 8, grid_h: 4, position: 6, configuration: {} },
  { id: 'virtual-forecast', title: 'Transparent trend projection', widget_type: 'insight', kpi_key: 'emissions_total', dimension: 'forecast', grid_w: 4, grid_h: 4, position: 7, configuration: {} },
  { id: 'virtual-insights', title: 'Calculation insights', widget_type: 'insight', kpi_key: 'emissions_total', dimension: 'insights', grid_w: 6, grid_h: 3, position: 8, configuration: {} },
  { id: 'virtual-scenarios', title: 'Scenario comparison', widget_type: 'insight', kpi_key: 'emissions_total', dimension: 'scenario', grid_w: 6, grid_h: 3, position: 9, configuration: {} },
];

function filters(value: any): AnalyticsFilters {
  const strings = (item: unknown) => Array.isArray(item) ? item.filter((entry): entry is string => typeof entry === 'string').slice(0, 100) : undefined;
  return { dateFrom: str(value?.dateFrom) || undefined, dateTo: str(value?.dateTo) || undefined, facilityIds: strings(value?.facilityIds), scopes: strings(value?.scopes), sources: strings(value?.sources) };
}

async function definitions(organisationId: string) {
  const { data, error } = await supabaseAdmin.from('analytics_kpi_definitions').select('*').in('status', ['active','draft']).or(`organisation_id.is.null,organisation_id.eq.${organisationId}`).order('is_system', { ascending: false }).order('name');
  if (error) throw new Error(error.message); return data ?? [];
}

export function createAnalyticsRouter() {
  const router = Router();
  router.get('/analytics/catalog', requireAuth, requirePermission('analytics.view'), async (req: AuthenticatedRequest, res) => {
    try { const organisationId = req.authorization!.organisationId; const [datasetResult, kpis, dashboardResult, viewResult, bookmarkResult, facilityResult, studioEntitlement, forecastingEntitlement] = await Promise.all([
      supabaseAdmin.from('analytics_datasets').select('*').eq('status','active').order('name'), definitions(organisationId),
      supabaseAdmin.from('analytics_dashboards').select('*, analytics_widgets(*)').eq('organisation_id',organisationId).is('deleted_at',null).neq('status','archived').order('updated_at',{ascending:false}),
      supabaseAdmin.from('analytics_saved_views').select('*').eq('organisation_id',organisationId).eq('user_id',req.authUser!.id).order('name'),
      supabaseAdmin.from('analytics_bookmarks').select('*').eq('organisation_id',organisationId).eq('user_id',req.authUser!.id).order('created_at',{ascending:false}),
      supabaseAdmin.from('facilities').select('id,name,location').eq('organisation_id',organisationId).is('deleted_at',null).order('name'),
      getEntitlement(organisationId,'analytics.studio'),getEntitlement(organisationId,'analytics.forecasting'),
    ]); const error=datasetResult.error??dashboardResult.error??viewResult.error??bookmarkResult.error??facilityResult.error;if(error)throw new Error(error.message);
      const availableWidgets=forecastingEntitlement?.enabled?defaultWidgets:defaultWidgets.filter(widget=>widget.dimension!=='forecast');
      const dashboards = dashboardResult.data?.length ? dashboardResult.data : [{ id:'analytics-default',name:'Carbon Performance',description:'Governed operational carbon analytics.',dashboard_type:'executive',visibility:'organisation',status:'published',is_default:true,filters:{},analytics_widgets:availableWidgets,virtual:true }];
      res.json({datasets:datasetResult.data??[],kpis,dashboards,savedViews:viewResult.data??[],bookmarks:bookmarkResult.data??[],facilities:facilityResult.data??[],features:{studio:Boolean(studioEntitlement?.enabled),forecasting:Boolean(forecastingEntitlement?.enabled)}});
    } catch(error){res.status(500).json({error:error instanceof Error?error.message:'Unable to load analytics catalog.'});}
  });

  router.post('/analytics/query', requireAuth, requirePermission('analytics.view'), requireEntitlement('analytics.trends'), async (req: AuthenticatedRequest,res)=>{try{const organisationId=req.authorization!.organisationId,data=await buildAnalyticsDataset(organisationId,filters(req.body?.filters),await definitions(organisationId));if(!(await getEntitlement(organisationId,'analytics.forecasting'))?.enabled)data.forecast=[];res.json({data});}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Unable to query analytics.'});}});

  router.post('/analytics/explain', requireAuth, requirePermission('analytics.view'), requirePermission('ai.use'), requireEntitlement('analytics.calculation_insights'), async(req:AuthenticatedRequest,res)=>{try{if(!runtimeConfig.ai.enabled||runtimeConfig.ai.provider!=='ollama')return res.status(503).json({error:'Local Carbon Copilot is disabled.'});const organisationId=req.authorization!.organisationId,dataset=await buildAnalyticsDataset(organisationId,filters(req.body?.filters),await definitions(organisationId));const citations=dataset.kpis.map((kpi:any)=>({id:`kpi:${kpi.key}`,label:kpi.name,value:kpi.value,unit:kpi.unit}));const provider=new OllamaProvider(runtimeConfig.ai.baseUrl,runtimeConfig.ai.model,runtimeConfig.ai.contextLength,runtimeConfig.ai.timeoutMs);const result=await provider.generate({system:'Explain governed carbon analytics using only the supplied aggregates. Do not infer causality, compliance, assurance, missing values, industry performance, or future outcomes. A projection is not a forecast guarantee. Cite KPI IDs.',question:str(req.body?.question)||'Explain the most material changes, concentrations, data limitations, and sensible investigation priorities.',history:[],context:{generatedAt:dataset.generatedAt,filters:dataset.filters,kpis:citations,monthly:dataset.series.monthly,facilities:dataset.series.facility,source:dataset.series.source,benchmark:dataset.benchmark,deterministicInsights:dataset.insights}});const allowed=new Set(citations.map(item=>item.id)),used=citations.filter(item=>result.citationIds.includes(item.id)&&allowed.has(item.id));await supabaseAdmin.from('ai_usage_events').insert({id:`ai-usage-${randomUUID()}`,organisation_id:organisationId,user_id:req.authUser!.id,provider:'ollama',model:runtimeConfig.ai.model,status:'completed',prompt_tokens:result.promptTokens??null,completion_tokens:result.completionTokens??null,duration_ms:result.durationMs,metadata:{surface:'analytics',citationCount:used.length}});res.json({explanation:{answer:result.answer,citations:used,suggestedActions:result.suggestedActions,limitations:result.limitations,model:runtimeConfig.ai.model}});}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Unable to explain analytics.'});}});

  router.post('/analytics/kpis', requireAuth, requireOperationalLicense, requirePermission('analytics.edit'), requireEntitlement('analytics.studio'), async(req:AuthenticatedRequest,res)=>{try{const body=req.body??{},key=str(body.key).toLowerCase().replace(/[^a-z0-9_]+/g,'_'),name=str(body.name),formula=str(body.formula);if(!key||!name||!formula)return res.status(400).json({error:'KPI key, name and formula are required.'});const {data:reserved}=await supabaseAdmin.from('analytics_kpi_definitions').select('id').eq('key',key).is('organisation_id',null).maybeSingle();if(reserved)return res.status(409).json({error:'System KPI keys cannot be overridden.'});evaluateAnalyticsFormula(formula,baseVariables);const {data,error}=await supabaseAdmin.from('analytics_kpi_definitions').insert({id:`analytics-kpi-${randomUUID()}`,organisation_id:req.authorization!.organisationId,dataset_id:'analytics-dataset-carbon-ledger',key,name,description:str(body.description),category:str(body.category)||'Custom',formula,unit:str(body.unit),format:['number','decimal','percent','currency'].includes(str(body.format))?str(body.format):'decimal',direction:['higher-better','lower-better','neutral'].includes(str(body.direction))?str(body.direction):'neutral',is_system:false,status:'active',created_by:req.authUser!.id}).select('*').single();if(error)throw new Error(error.message);res.status(201).json({kpi:data});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to create KPI.'});}});

  router.post('/analytics/dashboards', requireAuth, requireOperationalLicense, requirePermission('analytics.edit'), requireEntitlement('analytics.studio'), async(req:AuthenticatedRequest,res)=>{const name=str(req.body?.name);if(!name)return res.status(400).json({error:'Dashboard name is required.'});const {data,error}=await supabaseAdmin.from('analytics_dashboards').insert({id:`analytics-dashboard-${randomUUID()}`,organisation_id:req.authorization!.organisationId,owner_user_id:req.authUser!.id,name,description:str(req.body?.description),dashboard_type:['executive','operational','facility','custom'].includes(str(req.body?.dashboardType))?str(req.body.dashboardType):'custom',visibility:str(req.body?.visibility)==='organisation'?'organisation':'private',filters:filters(req.body?.filters),status:'draft'}).select('*').single();if(error)return res.status(500).json({error:error.message});res.status(201).json({dashboard:{...data,analytics_widgets:[]}});});

  router.put('/analytics/dashboards/:id', requireAuth, requireOperationalLicense, requirePermission('analytics.edit'), requireEntitlement('analytics.studio'), async(req:AuthenticatedRequest,res)=>{try{const organisationId=req.authorization!.organisationId;const {data:existing}=await supabaseAdmin.from('analytics_dashboards').select('id').eq('id',req.params.id).eq('organisation_id',organisationId).maybeSingle();if(!existing)return res.status(404).json({error:'Dashboard not found.'});const widgets=Array.isArray(req.body?.widgets)?req.body.widgets.slice(0,40):[];const dashboardUpdate=await supabaseAdmin.from('analytics_dashboards').update({name:str(req.body?.name)||'Analytics dashboard',description:str(req.body?.description),visibility:str(req.body?.visibility)==='organisation'?'organisation':'private',filters:filters(req.body?.filters),status:str(req.body?.status)==='published'?'published':'draft'}).eq('id',req.params.id).eq('organisation_id',organisationId);if(dashboardUpdate.error)throw new Error(dashboardUpdate.error.message);const deletion=await supabaseAdmin.from('analytics_widgets').delete().eq('dashboard_id',req.params.id).eq('organisation_id',organisationId);if(deletion.error)throw new Error(deletion.error.message);if(widgets.length){const rows=widgets.map((widget:any,position:number)=>{const type=str(widget.widget_type,widget.widgetType);if(!widgetTypes.has(type))throw new Error(`Unsupported widget type: ${type}.`);return{id:`analytics-widget-${randomUUID()}`,organisation_id:organisationId,dashboard_id:req.params.id,title:str(widget.title)||'Untitled widget',widget_type:type,kpi_key:str(widget.kpi_key,widget.kpiKey),dimension:str(widget.dimension),configuration:widget.configuration??{},grid_x:Number(widget.grid_x??0),grid_y:Number(widget.grid_y??0),grid_w:Math.max(2,Math.min(12,Number(widget.grid_w??4))),grid_h:Math.max(2,Math.min(12,Number(widget.grid_h??3))),position};});const insertion=await supabaseAdmin.from('analytics_widgets').insert(rows);if(insertion.error)throw new Error(insertion.error.message);}const {data,error}=await supabaseAdmin.from('analytics_dashboards').select('*,analytics_widgets(*)').eq('id',req.params.id).single();if(error)throw new Error(error.message);res.json({dashboard:data});}catch(error){res.status(400).json({error:error instanceof Error?error.message:'Unable to save dashboard.'});}});

  router.post('/analytics/saved-views', requireAuth, requirePermission('analytics.view'), async(req:AuthenticatedRequest,res)=>{const name=str(req.body?.name);if(!name)return res.status(400).json({error:'View name is required.'});const organisationId=req.authorization!.organisationId,id=`analytics-view-${req.authUser!.id}-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;const {data,error}=await supabaseAdmin.from('analytics_saved_views').upsert({id,organisation_id:organisationId,user_id:req.authUser!.id,name,filters:filters(req.body?.filters),is_default:Boolean(req.body?.isDefault)},{onConflict:'organisation_id,user_id,name'}).select('*').single();if(error)return res.status(500).json({error:error.message});res.status(201).json({savedView:data});});
  router.post('/analytics/bookmarks', requireAuth, requirePermission('analytics.view'), async(req:AuthenticatedRequest,res)=>{const name=str(req.body?.name),dashboardId=str(req.body?.dashboardId);if(!name||!dashboardId)return res.status(400).json({error:'Bookmark name and dashboard are required.'});const organisationId=req.authorization!.organisationId,{data:dashboard}=await supabaseAdmin.from('analytics_dashboards').select('id').eq('id',dashboardId).eq('organisation_id',organisationId).maybeSingle();if(!dashboard)return res.status(404).json({error:'Persist the dashboard before bookmarking it.'});const {data,error}=await supabaseAdmin.from('analytics_bookmarks').insert({id:`analytics-bookmark-${randomUUID()}`,organisation_id:organisationId,user_id:req.authUser!.id,dashboard_id:dashboardId,name,state:req.body?.state??{}}).select('*').single();if(error)return res.status(500).json({error:error.message});res.status(201).json({bookmark:data});});
  router.post('/analytics/export', requireAuth, requirePermission('analytics.view'), async(req:AuthenticatedRequest,res)=>{try{const organisationId=req.authorization!.organisationId,format=str(req.body?.format)==='json'?'json':'csv',data=await buildAnalyticsDataset(organisationId,filters(req.body?.filters),await definitions(organisationId)),id=`analytics-export-${randomUUID()}`;await supabaseAdmin.from('analytics_exports').insert({id,organisation_id:organisationId,dashboard_id:str(req.body?.dashboardId)||null,format,filters:filters(req.body?.filters),exported_by:req.authUser!.id});let content:string,mimeType:string,filename:string;if(format==='json'){content=JSON.stringify(data,null,2);mimeType='application/json';filename='carbon-analytics.json';}else{const columns=['date','facility','scope','source','quantity','unit','emissionsTco2e','status','factorVersion','evidenceCount'];content=[columns.join(','),...data.drillRows.map((row:any)=>columns.map((key)=>`"${String(row[key]??'').replaceAll('"','""')}"`).join(','))].join('\n');mimeType='text/csv';filename='carbon-analytics.csv';}res.json({export:{id,filename,mimeType,contentBase64:Buffer.from(content).toString('base64')}});}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Unable to export analytics.'});}});
  return router;
}
