import { Router } from 'express';
import { randomUUID } from 'node:crypto';
import { type AuthenticatedRequest, requireAuth, requirePermission } from '../auth.js';
import { parseCsv, parseExcel, suggestMapping, transformRows } from '../dataIngestion.js';
import { str } from '../requestUtils.js';
import { supabaseAdmin } from '../supabaseClients.js';
import { postStagedRecord } from '../operationalPostingService.js';

async function sourceDefinition(key: string) { const { data, error } = await supabaseAdmin.from('data_source_definitions').select('*').eq('source_key', key).eq('status', 'active').maybeSingle(); if (error || !data) throw new Error(error?.message ?? 'Data source definition not found.'); return data; }
async function ownJob(organisationId: string, id: string) { const { data, error } = await supabaseAdmin.from('data_import_jobs').select('*').eq('id', id).eq('organisation_id', organisationId).is('deleted_at', null).maybeSingle(); if (error || !data) throw new Error(error?.message ?? 'Import job not found.'); return data; }

export function createDataPlatformRouter() {
  const router = Router();
  router.get('/data-platform/connectors', requireAuth, requirePermission('data.read'), async (_req, res) => { const { data, error } = await supabaseAdmin.from('data_connector_catalog').select('*').neq('status', 'disabled').order('category').order('name'); if (error) return res.status(500).json({ error: error.message }); res.json({ connectors: data ?? [] }); });
  router.get('/data-platform/sources', requireAuth, requirePermission('data.read'), async (_req, res) => { const { data, error } = await supabaseAdmin.from('data_source_definitions').select('*').eq('status', 'active').order('category').order('name'); if (error) return res.status(500).json({ error: error.message }); res.json({ sources: data ?? [] }); });
  router.get('/data-platform/jobs', requireAuth, requirePermission('data.read'), async (req: AuthenticatedRequest, res) => { const { data, error } = await supabaseAdmin.from('data_import_jobs').select('*, data_source_definitions(source_key,name,category)').eq('organisation_id', req.authorization!.organisationId).is('deleted_at', null).order('created_at', { ascending: false }).limit(50); if (error) return res.status(500).json({ error: error.message }); res.json({ jobs: data ?? [] }); });
  router.get('/data-platform/staging', requireAuth, requirePermission('data.read'), async (req: AuthenticatedRequest, res) => { let query = supabaseAdmin.from('ingested_records').select('*, data_source_definitions(source_key,name,category), data_import_jobs(filename)').eq('organisation_id', req.authorization!.organisationId).is('deleted_at', null).order('created_at', { ascending: false }).limit(200); if (typeof req.query.status === 'string' && req.query.status !== 'all') query = query.eq('status', req.query.status); const { data, error } = await query; if (error) return res.status(500).json({ error: error.message }); res.json({ records: data ?? [] }); });
  router.post('/data-platform/staging/:id/review', requireAuth, requirePermission('data.approve'), async (req: AuthenticatedRequest, res) => { try { const action = str(req.body?.action); if (!['approved','rejected'].includes(action)) return res.status(400).json({ error: 'Review action must be approved or rejected.' }); const { data: before } = await supabaseAdmin.from('ingested_records').select('*').eq('id', req.params.id).eq('organisation_id', req.authorization!.organisationId).maybeSingle(); if (!before || before.status !== 'staged') return res.status(409).json({ error: 'Only staged records can be reviewed.' }); const { data, error } = await supabaseAdmin.from('ingested_records').update({ status: action }).eq('id', before.id).select('*').single(); if (error) throw new Error(error.message); await supabaseAdmin.from('data_record_versions').insert({ id: `data-version-${randomUUID()}`, ingested_record_id: before.id, version_number: 1, snapshot: data, change_reason: `${action} by staging reviewer`, created_by: req.authUser!.id }); res.json({ record: data }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to review staged record.' }); } });
  router.post('/data-platform/staging/:id/post', requireAuth, requirePermission('data.approve'), async (req: AuthenticatedRequest, res) => { try { const { data: record, error } = await supabaseAdmin.from('ingested_records').select('*').eq('id', req.params.id).eq('organisation_id', req.authorization!.organisationId).maybeSingle(); if (error || !record) return res.status(404).json({ error: error?.message ?? 'Staged record not found.' }); if (record.status !== 'approved') return res.status(409).json({ error: 'The staged record must be approved before posting.' }); const posted = await postStagedRecord({ organisationId: req.authorization!.organisationId, userId: req.authUser!.id, stagedRecord: record }); const { data: updated, error: updateError } = await supabaseAdmin.from('ingested_records').update({ status: 'posted', record_data: { ...record.record_data, operationalPosting: posted } }).eq('id', record.id).select('*').single(); if (updateError) throw new Error(updateError.message); await supabaseAdmin.from('data_record_versions').insert({ id: `data-version-${randomUUID()}`, ingested_record_id: record.id, version_number: 2, snapshot: updated, change_reason: `Posted to ${posted.target}`, created_by: req.authUser!.id }); res.json({ record: updated, posted }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to post staged record.' }); } });
  router.get('/data-platform/jobs/:id', requireAuth, requirePermission('data.read'), async (req: AuthenticatedRequest, res) => { try { const job = await ownJob(req.authorization!.organisationId, req.params.id); const [{ data: rows, error: rowError }, { data: issues, error: issueError }, { data: runs, error: runError }] = await Promise.all([supabaseAdmin.from('data_import_rows').select('*').eq('import_job_id', job.id).order('row_number').limit(500), supabaseAdmin.from('data_quality_issues').select('*').eq('import_job_id', job.id).order('created_at'), supabaseAdmin.from('data_pipeline_runs').select('*, data_pipeline_events(*)').eq('import_job_id', job.id).order('created_at', { ascending: false })]); if (rowError || issueError || runError) throw new Error(rowError?.message ?? issueError?.message ?? runError?.message); res.json({ job, rows: rows ?? [], issues: issues ?? [], runs: runs ?? [] }); } catch (error) { res.status(404).json({ error: error instanceof Error ? error.message : 'Import job not found.' }); } });
  router.post('/data-platform/imports/preview', requireAuth, requirePermission('data.import'), async (req: AuthenticatedRequest, res) => {
    try {
      const body = req.body ?? {}; const content = str(body.content); const filename = str(body.filename) || 'data.csv'; const isExcel = /\.xlsx$/i.test(filename); const source = await sourceDefinition(str(body.sourceKey)); if (!content && !str(body.contentBase64)) return res.status(400).json({ error: 'CSV content or an Excel workbook is required.' });
      const parsed = isExcel ? await parseExcel(Buffer.from(str(body.contentBase64), 'base64')) : parseCsv(content); if (parsed.rows.length > 5000) return res.status(413).json({ error: 'A preview import is limited to 5,000 rows.' }); const mapping = body.mapping && typeof body.mapping === 'object' ? body.mapping : suggestMapping(parsed.headers, source); const transformed = transformRows(parsed.rows, mapping, source);
      const facilityIds = [...new Set(transformed.map((row) => str(row.normalizedData.facility_id)).filter(Boolean))]; const { data: facilities, error: facilitiesError } = facilityIds.length ? await supabaseAdmin.from('facilities').select('id').eq('organisation_id', req.authorization!.organisationId).in('id', facilityIds) : { data: [], error: null }; if (facilitiesError) throw new Error(facilitiesError.message); const validFacilityIds = new Set((facilities ?? []).map((facility: any) => facility.id)); for (const row of transformed) { const facilityId = str(row.normalizedData.facility_id); if (facilityId && !validFacilityIds.has(facilityId)) { row.issues.push({ field: 'facility_id', code: 'invalid_reference', severity: 'error', message: `Facility ${facilityId} does not exist in this organisation.` }); row.status = 'invalid'; row.confidenceScore = Math.max(0, row.confidenceScore - 30); } }
      const validCount = transformed.filter((row) => row.status === 'valid').length; const duplicateCount = transformed.filter((row) => row.status === 'duplicate').length; const invalidCount = transformed.length - validCount - duplicateCount; const confidenceScore = transformed.length ? transformed.reduce((sum, row) => sum + row.confidenceScore, 0) / transformed.length : 0; const jobId = `data-import-${randomUUID()}`;
      const { error: jobError } = await supabaseAdmin.from('data_import_jobs').insert({ id: jobId, organisation_id: req.authorization!.organisationId, source_definition_id: source.id, filename, format: isExcel ? 'excel' : 'csv', status: validCount ? 'ready' : 'mapping', row_count: transformed.length, valid_count: validCount, invalid_count: invalidCount, duplicate_count: duplicateCount, confidence_score: confidenceScore, source_headers: parsed.headers, mapping_snapshot: mapping, created_by: req.authUser!.id }); if (jobError) throw new Error(jobError.message);
      const rows = transformed.map((row) => ({ id: `data-row-${randomUUID()}`, import_job_id: jobId, row_number: row.rowNumber, source_data: row.sourceData, mapped_data: row.mappedData, normalized_data: row.normalizedData, status: row.status, confidence_score: row.confidenceScore, duplicate_signature: row.duplicateSignature, issues: row.issues })); const { data: insertedRows, error: rowError } = await supabaseAdmin.from('data_import_rows').insert(rows).select('id,row_number,status,issues,source_data,mapped_data,normalized_data,confidence_score'); if (rowError) throw new Error(rowError.message);
      const issueRows = (insertedRows ?? []).flatMap((row: any) => (row.issues ?? []).map((issue: any) => ({ id: `data-issue-${randomUUID()}`, organisation_id: req.authorization!.organisationId, import_job_id: jobId, import_row_id: row.id, field_name: issue.field, issue_code: issue.code, severity: issue.severity, message: issue.message }))); if (issueRows.length) { const { error } = await supabaseAdmin.from('data_quality_issues').insert(issueRows); if (error) throw new Error(error.message); }
      res.status(201).json({ job: { id: jobId, filename, status: validCount ? 'ready' : 'mapping', rowCount: transformed.length, validCount, invalidCount, duplicateCount, confidenceScore, headers: parsed.headers, mapping }, rows: insertedRows ?? [] });
    } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to preview import.' }); }
  });
  router.post('/data-platform/jobs/:id/commit', requireAuth, requirePermission('data.import'), async (req: AuthenticatedRequest, res) => {
    try { const job = await ownJob(req.authorization!.organisationId, req.params.id); const { data: source } = await supabaseAdmin.from('data_source_definitions').select('*').eq('id', job.source_definition_id).single(); const { data: rows, error: rowsError } = await supabaseAdmin.from('data_import_rows').select('*').eq('import_job_id', job.id).eq('status', 'valid'); if (rowsError) throw new Error(rowsError.message); const runId = `data-run-${randomUUID()}`; await supabaseAdmin.from('data_pipeline_runs').insert({ id: runId, organisation_id: req.authorization!.organisationId, import_job_id: job.id, status: 'processing', started_at: new Date().toISOString(), created_by: req.authUser!.id }); await supabaseAdmin.from('data_pipeline_events').insert({ id: `data-event-${randomUUID()}`, pipeline_run_id: runId, event_type: 'started', message: 'Validated rows entered the staging ledger.' });
      const records = (rows ?? []).map((row: any) => ({ id: `ingested-${randomUUID()}`, organisation_id: req.authorization!.organisationId, source_definition_id: job.source_definition_id, import_job_id: job.id, import_row_id: row.id, target_entity_key: source?.target_entity_key ?? 'unknown', external_record_id: str(row.normalized_data?.external_record_id), record_data: row.mapped_data, canonical_data: row.normalized_data, duplicate_signature: row.duplicate_signature, quality_score: row.confidence_score, status: 'staged', created_by: req.authUser!.id })); let imported = 0; if (records.length) { const { data, error } = await supabaseAdmin.from('ingested_records').upsert(records, { onConflict: 'organisation_id,duplicate_signature', ignoreDuplicates: true }).select('id'); if (error) throw new Error(error.message); imported = data?.length ?? 0; }
      const duplicatesSkipped = records.length - imported; await supabaseAdmin.from('data_import_rows').update({ status: imported ? 'imported' : 'duplicate' }).eq('import_job_id', job.id).eq('status', 'valid'); await supabaseAdmin.from('data_import_jobs').update({ status: imported === records.length ? 'completed' : 'partial', duplicate_count: Number(job.duplicate_count ?? 0) + duplicatesSkipped, completed_at: new Date().toISOString() }).eq('id', job.id); await supabaseAdmin.from('data_pipeline_runs').update({ status: imported === records.length ? 'completed' : 'partial', completed_at: new Date().toISOString(), metrics: { submitted: records.length, imported, duplicatesSkipped } }).eq('id', runId); await supabaseAdmin.from('data_pipeline_events').insert({ id: `data-event-${randomUUID()}`, pipeline_run_id: runId, event_type: 'completed', message: `${imported} rows added and ${duplicatesSkipped} existing duplicates skipped.`, details: { imported, duplicatesSkipped } }); res.json({ run: { id: runId, status: imported === records.length ? 'completed' : 'partial', submitted: records.length, imported, duplicatesSkipped } });
    } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to commit import.' }); }
  });
  router.post('/data-platform/connections', requireAuth, requirePermission('data.connect'), async (req: AuthenticatedRequest, res) => { try { const body = req.body ?? {}; const connectorKey = str(body.connectorKey); const { data: connector } = await supabaseAdmin.from('data_connector_catalog').select('*').eq('connector_key', connectorKey).maybeSingle(); if (!connector) return res.status(400).json({ error: 'Connector not found.' }); const { data, error } = await supabaseAdmin.from('data_connections').insert({ id: `data-connection-${randomUUID()}`, organisation_id: req.authorization!.organisationId, connector_id: connector.id, name: str(body.name) || connector.name, status: 'draft', credential_reference: str(body.credentialReference), configuration: body.configuration ?? {}, created_by: req.authUser!.id }).select('*').single(); if (error) throw new Error(error.message); res.status(201).json({ connection: data, credentialStored: false }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to configure connector.' }); } });
  router.get('/data-platform/connections', requireAuth, requirePermission('data.read'), async (req: AuthenticatedRequest, res) => { const { data, error } = await supabaseAdmin.from('data_connections').select('*, data_connector_catalog(connector_key,name,category,status)').eq('organisation_id', req.authorization!.organisationId).is('deleted_at', null).order('created_at', { ascending: false }); if (error) return res.status(500).json({ error: error.message }); res.json({ connections: data ?? [] }); });
  router.post('/data-platform/mappings', requireAuth, requirePermission('data.manage'), async (req: AuthenticatedRequest, res) => { try { const body = req.body ?? {}; const source = await sourceDefinition(str(body.sourceKey)); const mapping = body.mapping && typeof body.mapping === 'object' ? body.mapping : {}; if (!Object.keys(mapping).length) return res.status(400).json({ error: 'At least one column mapping is required.' }); const mappingId = `data-mapping-${randomUUID()}`; const { data, error } = await supabaseAdmin.from('data_mappings').insert({ id: mappingId, organisation_id: req.authorization!.organisationId, source_definition_id: source.id, name: str(body.name) || `${source.name} mapping`, description: str(body.description), status: 'published', created_by: req.authUser!.id }).select('*').single(); if (error || !data) throw new Error(error?.message ?? 'Unable to save mapping.'); const rows = Object.entries(mapping).filter(([, target]) => Boolean(target)).map(([sourceColumn, targetField], position) => ({ id: `data-mapping-field-${randomUUID()}`, mapping_id: mappingId, source_column: sourceColumn, target_field: String(targetField), position })); if (rows.length) { const { error: rowError } = await supabaseAdmin.from('data_mapping_fields').insert(rows); if (rowError) throw new Error(rowError.message); } res.status(201).json({ mapping: { ...data, fields: rows } }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to save mapping.' }); } });
  router.get('/data-platform/mappings', requireAuth, requirePermission('data.read'), async (req: AuthenticatedRequest, res) => { const { data, error } = await supabaseAdmin.from('data_mappings').select('*, data_mapping_fields(*), data_source_definitions(source_key,name)').eq('organisation_id', req.authorization!.organisationId).is('deleted_at', null).neq('status', 'archived').order('updated_at', { ascending: false }); if (error) return res.status(500).json({ error: error.message }); res.json({ mappings: data ?? [] }); });
  router.post('/data-platform/jobs/:id/retry', requireAuth, requirePermission('data.import'), async (req: AuthenticatedRequest, res) => { try { const job = await ownJob(req.authorization!.organisationId, req.params.id); if (!['failed','partial','ready'].includes(job.status)) return res.status(409).json({ error: 'Only failed, partial, or ready jobs can be retried.' }); const { data, error } = await supabaseAdmin.from('data_import_jobs').update({ status: 'ready', retry_count: Number(job.retry_count ?? 0) + 1, completed_at: null }).eq('id', job.id).select('*').single(); if (error) throw new Error(error.message); res.json({ job: data }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to retry import.' }); } });
  router.post('/data-platform/staging/:id/reject', requireAuth, requirePermission('data.approve'), async (req: AuthenticatedRequest, res) => { try { const { data: record, error } = await supabaseAdmin.from('ingested_records').select('*').eq('id', req.params.id).eq('organisation_id', req.authorization!.organisationId).maybeSingle(); if (error || !record) return res.status(404).json({ error: error?.message ?? 'Staged record not found.' }); if (!['staged','approved'].includes(record.status)) return res.status(409).json({ error: 'Only staged or approved records can be rejected.' }); const { data, error: updateError } = await supabaseAdmin.from('ingested_records').update({ status: 'rejected' }).eq('id', record.id).select('*').single(); if (updateError) throw new Error(updateError.message); res.json({ record: data }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Unable to reject record.' }); } });
  router.get('/data-platform/operational/:ledger', requireAuth, requirePermission('data.read'), async (req: AuthenticatedRequest, res) => { const tables: Record<string,string> = { water: 'water_records', waste: 'waste_records', material: 'material_records', air: 'air_emission_records' }; const table = tables[req.params.ledger]; if (!table) return res.status(400).json({ error: 'Ledger must be water, waste, material, or air.' }); const { data, error } = await supabaseAdmin.from(table).select('*').eq('organisation_id', req.authorization!.organisationId).is('deleted_at', null).order('date', { ascending: false }).limit(200); if (error) return res.status(500).json({ error: error.message }); res.json({ records: data ?? [] }); });
  return router;
}
