import {Router,type NextFunction,type Request,type Response} from 'express';
import {randomUUID} from 'node:crypto';
import {type AuthenticatedRequest,requireAuth,requirePermission} from '../auth.js';
import {getEntitlement,getLicense,isOperationalLicense} from '../entitlementService.js';
import {requireEntitlement,requireOperationalLicense} from '../middleware/entitlements.js';
import {createApiCredential,createWebhookSecret,hashSecret,normalizeEvents,normalizeScopes,safeMarketplaceManifest,validWebhookUrl} from '../marketplaceSecurity.js';
import {str} from '../requestUtils.js';
import {supabaseAdmin} from '../supabaseClients.js';

type DeveloperRequest=Request&{developer?:{organisationId:string;credentialId:string;scopes:string[]}};
const buckets=new Map<string,{minute:number;count:number}>();
async function requireApiKey(req:DeveloperRequest,res:Response,next:NextFunction){try{const secret=str(req.headers['x-api-key']);if(!secret.startsWith('bc_live_'))return res.status(401).json({error:'A valid x-api-key header is required.'});const hash=hashSecret(secret),{data:key}=await supabaseAdmin.from('developer_api_credentials').select('*').eq('secret_hash',hash).eq('status','active').maybeSingle();if(!key||key.expires_at&&new Date(key.expires_at).getTime()<Date.now())return res.status(401).json({error:'API credential is invalid or expired.'});const [license,entitlement]=await Promise.all([getLicense(key.organisation_id),getEntitlement(key.organisation_id,'integration.developer_api')]);if(!isOperationalLicense(license)||!entitlement?.enabled)return res.status(403).json({error:'Developer API is not enabled for this organisation.'});const minute=Math.floor(Date.now()/60000),bucket=buckets.get(key.id);if(!bucket||bucket.minute!==minute)buckets.set(key.id,{minute,count:1});else if(++bucket.count>60)return res.status(429).json({error:'API rate limit exceeded. Limit: 60 requests per minute.'});req.developer={organisationId:key.organisation_id,credentialId:key.id,scopes:Array.isArray(key.scopes)?key.scopes:[]};await supabaseAdmin.from('developer_api_credentials').update({last_used_at:new Date().toISOString()}).eq('id',key.id);next()}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Developer authentication failed.'})}}
function requireScope(scope:string){return(req:DeveloperRequest,res:Response,next:NextFunction)=>req.developer?.scopes.includes(scope)?next():res.status(403).json({error:'API credential lacks the required scope.',scope})}
async function usage(req:DeveloperRequest,status:number){await supabaseAdmin.from('developer_api_usage').insert({id:`developer-usage-${randomUUID()}`,organisation_id:req.developer!.organisationId,credential_id:req.developer!.credentialId,route:req.path,status_code:status,request_id:str(req.headers['x-request-id'])})}

export function createMarketplaceRouter(){const router=Router();
 router.get('/marketplace/workspace',requireAuth,requirePermission('marketplace.view'),requireEntitlement('marketplace.catalog'),async(req:AuthenticatedRequest,res)=>{try{const org=req.authorization!.organisationId,[catalog,installations,keys,webhooks,deliveries,usageRows]=await Promise.all([supabaseAdmin.from('marketplace_items').select('*').neq('status','disabled').order('category').order('name'),supabaseAdmin.from('marketplace_installations').select('*,marketplace_items(item_key,name,category,status,version)').eq('organisation_id',org).neq('status','uninstalled').order('installed_at',{ascending:false}),supabaseAdmin.from('developer_api_credentials').select('id,name,key_prefix,scopes,status,expires_at,last_used_at,created_at').eq('organisation_id',org).order('created_at',{ascending:false}),supabaseAdmin.from('webhook_subscriptions').select('id,name,endpoint_url,event_types,status,api_version,created_at,last_delivery_at').eq('organisation_id',org).order('created_at',{ascending:false}),supabaseAdmin.from('webhook_deliveries').select('*').eq('organisation_id',org).order('created_at',{ascending:false}).limit(50),supabaseAdmin.from('developer_api_usage').select('*').eq('organisation_id',org).order('occurred_at',{ascending:false}).limit(100)]);const all=[catalog,installations,keys,webhooks,deliveries,usageRows] as any[],error=all.find(x=>x.error)?.error;if(error)throw new Error(error.message);res.json({catalog:(catalog.data??[]).map((item:any)=>({...item,manifest:safeMarketplaceManifest(item.manifest)})),installations:installations.data??[],apiCredentials:keys.data??[],webhooks:webhooks.data??[],deliveries:deliveries.data??[],usage:usageRows.data??[],capabilities:{apiKeyDelivery:'secret shown once; hash stored',webhookDelivery:false,externalConnectors:false,arbitraryCode:false}})}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Unable to load marketplace.'})}});
 router.post('/marketplace/installations',requireAuth,requireOperationalLicense,requirePermission('marketplace.manage'),requireEntitlement('marketplace.catalog'),async(req:AuthenticatedRequest,res)=>{try{const org=req.authorization!.organisationId,itemId=str(req.body?.itemId),{data:item}=await supabaseAdmin.from('marketplace_items').select('*').eq('id',itemId).in('status',['available','preview']).single();if(!item)return res.status(404).json({error:'Marketplace item is unavailable.'});const {data,error}=await supabaseAdmin.from('marketplace_installations').upsert({id:`market-install-${org}-${item.id}`,organisation_id:org,marketplace_item_id:item.id,installed_version:item.version,status:'installed',configuration:{preview:item.status==='preview',manifest:safeMarketplaceManifest(item.manifest)},installed_by:req.authUser!.id,installed_at:new Date().toISOString(),uninstalled_at:null},{onConflict:'organisation_id,marketplace_item_id'}).select('*').single();if(error)throw new Error(error.message);res.status(201).json({installation:data,note:item.status==='preview'?'Installed as a preview definition; no external system was connected.':'Declarative package installed.'})}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Unable to install package.'})}});
 router.delete('/marketplace/installations/:id',requireAuth,requireOperationalLicense,requirePermission('marketplace.manage'),requireEntitlement('marketplace.catalog'),async(req:AuthenticatedRequest,res)=>{const {data,error}=await supabaseAdmin.from('marketplace_installations').update({status:'uninstalled',uninstalled_at:new Date().toISOString()}).eq('id',req.params.id).eq('organisation_id',req.authorization!.organisationId).select('*').single();if(error)return res.status(404).json({error:error.message});res.json({installation:data})});
 router.post('/marketplace/api-credentials',requireAuth,requireOperationalLicense,requirePermission('developer.manage'),requireEntitlement('integration.developer_api'),async(req:AuthenticatedRequest,res)=>{const scopes=normalizeScopes(req.body?.scopes),name=str(req.body?.name);if(!name||!scopes.length)return res.status(400).json({error:'Credential name and at least one supported scope are required.'});const generated=createApiCredential(),{data,error}=await supabaseAdmin.from('developer_api_credentials').insert({id:`developer-key-${randomUUID()}`,organisation_id:req.authorization!.organisationId,name,key_prefix:generated.prefix,secret_hash:generated.hash,scopes,expires_at:str(req.body?.expiresAt)||null,created_by:req.authUser!.id}).select('id,name,key_prefix,scopes,status,expires_at,created_at').single();if(error)return res.status(500).json({error:error.message});res.status(201).json({credential:data,secret:generated.secret,warning:'This secret is shown once. Store it securely; Balancing Carbon stores only its hash.'})});
 router.delete('/marketplace/api-credentials/:id',requireAuth,requireOperationalLicense,requirePermission('developer.manage'),requireEntitlement('integration.developer_api'),async(req:AuthenticatedRequest,res)=>{const {data,error}=await supabaseAdmin.from('developer_api_credentials').update({status:'revoked',revoked_at:new Date().toISOString()}).eq('id',req.params.id).eq('organisation_id',req.authorization!.organisationId).select('id,status,revoked_at').single();if(error)return res.status(404).json({error:error.message});res.json({credential:data})});
 router.post('/marketplace/webhooks',requireAuth,requireOperationalLicense,requirePermission('webhooks.manage'),requireEntitlement('integration.developer_api'),async(req:AuthenticatedRequest,res)=>{const events=normalizeEvents(req.body?.eventTypes),url=str(req.body?.endpointUrl),name=str(req.body?.name);if(!name||!events.length||!validWebhookUrl(url))return res.status(400).json({error:'Name, HTTPS endpoint, and at least one supported event are required.'});const generated=createWebhookSecret(),{data,error}=await supabaseAdmin.from('webhook_subscriptions').insert({id:`webhook-${randomUUID()}`,organisation_id:req.authorization!.organisationId,name,endpoint_url:url,secret_hash:generated.hash,event_types:events,status:'paused',created_by:req.authUser!.id}).select('id,name,endpoint_url,event_types,status,api_version,created_at').single();if(error)return res.status(500).json({error:error.message});res.status(201).json({webhook:data,signingSecret:generated.secret,warning:'Delivery remains paused until a background delivery worker and encrypted signing-secret store are configured.'})});
 router.delete('/marketplace/webhooks/:id',requireAuth,requireOperationalLicense,requirePermission('webhooks.manage'),requireEntitlement('integration.developer_api'),async(req:AuthenticatedRequest,res)=>{const {data,error}=await supabaseAdmin.from('webhook_subscriptions').update({status:'disabled'}).eq('id',req.params.id).eq('organisation_id',req.authorization!.organisationId).select('id,status').single();if(error)return res.status(404).json({error:error.message});res.json({webhook:data})});
 router.get('/developer/openapi',requireAuth,requirePermission('marketplace.view'),(_req,res)=>res.json({openapi:'3.1.0',info:{title:'Balancing Carbon Developer API',version:'2026-07-01'},servers:[{url:'/api/developer/v1'}],security:[{ApiKeyAuth:[]}],components:{securitySchemes:{ApiKeyAuth:{type:'apiKey',in:'header',name:'x-api-key'}}},paths:{'/carbon-summary':{get:{summary:'Read organization carbon summary',security:[{ApiKeyAuth:[]}],responses:{'200':{description:'Scoped current carbon aggregate'}}}}}}));
 router.get('/developer/v1/carbon-summary',requireApiKey,requireScope('carbon.read'),async(req:DeveloperRequest,res)=>{try{const org=req.developer!.organisationId,{data,error}=await supabaseAdmin.from('calculation_records').select('emissions_t_co2e,activity_records!inner(scope)').eq('organisation_id',org).eq('status','current');if(error)throw new Error(error.message);const rows=data??[],byScope:{[key:string]:number}={};for(const row of rows){const scope=(row as any).activity_records?.scope??'unknown';byScope[scope]=(byScope[scope]??0)+Number(row.emissions_t_co2e??0)}const response={generatedAt:new Date().toISOString(),totalTco2e:Object.values(byScope).reduce((a,b)=>a+b,0),byScope,recordCount:rows.length,boundary:'Current calculation records for the API credential organization.'};await usage(req,200);res.json({data:response})}catch(e){await usage(req,500);res.status(500).json({error:e instanceof Error?e.message:'Unable to load carbon summary.'})}});
 return router;}
