import {Router} from 'express';
import {randomUUID} from 'node:crypto';
import {type AuthenticatedRequest,requireAuth,requirePermission} from '../auth.js';
import {requireEntitlement,requireOperationalLicense} from '../middleware/entitlements.js';
import {aggregateSupplierReadiness,normalizePortalSlug,publicationReadiness,validPortalSections} from '../publicPortalEngine.js';
import {str} from '../requestUtils.js';
import {supabaseAdmin} from '../supabaseClients.js';

const n=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0;
const cleanItems=(value:unknown)=>Array.isArray(value)?value.slice(0,30).map((item:any)=>({title:str(item?.title).slice(0,160),summary:str(item?.summary).slice(0,1200),date:str(item?.date).slice(0,30)})).filter(item=>item.title):[];

async function sources(org:string){
 const [reports,documents]=await Promise.all([
  supabaseAdmin.from('reports').select('id,title,type,period,summary,status,studio_status').eq('organisation_id',org).order('created_at',{ascending:false}),
  supabaseAdmin.from('documents').select('id,name,category,period,upload_date').eq('organisation_id',org).order('created_at',{ascending:false})
 ]);
 if(reports.error||documents.error)throw new Error(reports.error?.message??documents.error?.message);
 return{reports:reports.data??[],documents:documents.data??[]};
}

async function buildSnapshot(org:string,portal:any,assets:any[]){
 const [organization,calculations,esg,targets,pathways,suppliers]=await Promise.all([
  supabaseAdmin.from('organisations').select('name,industry,location,reporting_year,target_reduction_percent').eq('id',org).single(),
  supabaseAdmin.from('calculation_records').select('emissions_t_co2e,activity_records!inner(scope,verification_status)').eq('organisation_id',org).eq('status','current'),
  supabaseAdmin.from('esg_questions').select('category,score,status,review_status').eq('organisation_id',org).eq('review_status','Approved'),
  supabaseAdmin.from('sustainability_targets').select('id,name,target_type,baseline_year,target_year,baseline_value,target_value,current_value,unit,scopes,framework,status,methodology').eq('organisation_id',org).in('status',['approved','active','achieved']).order('target_year'),
  supabaseAdmin.from('net_zero_pathways').select('id,name,baseline_year,target_year,baseline_emissions_t_co2e,target_residual_t_co2e,reduction_hierarchy,status,pathway_milestones(year,target_emissions_t_co2e,status)').eq('organisation_id',org).in('status',['approved','active']).order('created_at',{ascending:false}),
  supabaseAdmin.from('supplier_sustainability_assessments').select('engagement_status,data_quality').eq('organisation_id',org)
 ]);
 const error=organization.error??calculations.error??esg.error??targets.error??pathways.error??suppliers.error;if(error)throw new Error(error.message);
 const calc=calculations.data??[],total=calc.reduce((sum,row)=>sum+n(row.emissions_t_co2e),0),scope1=calc.filter((row:any)=>row.activity_records?.scope==='scope-1').reduce((sum,row)=>sum+n(row.emissions_t_co2e),0),scope2=calc.filter((row:any)=>row.activity_records?.scope==='scope-2').reduce((sum,row)=>sum+n(row.emissions_t_co2e),0),scope3=calc.filter((row:any)=>row.activity_records?.scope==='scope-3').reduce((sum,row)=>sum+n(row.emissions_t_co2e),0),verified=calc.filter((row:any)=>['verified','approved'].includes(row.activity_records?.verification_status)).length;
 const approved=esg.data??[],score=approved.length?Math.round(approved.reduce((sum,row)=>sum+n(row.score),0)/approved.length):null,compliant=approved.filter(row=>row.status==='Compliant').length;
 const content=portal.content??{};
 return{
  schemaVersion:'public-esg-portal-v1',generatedAt:new Date().toISOString(),organization:organization.data,
  portal:{title:portal.title,summary:portal.summary,slug:portal.slug,sections:portal.enabled_sections,theme:portal.theme},
  carbon:{totalTco2e:total,scope1Tco2e:scope1,scope2Tco2e:scope2,scope3Tco2e:scope3,reportingYear:organization.data.reporting_year,verifiedCalculationShare:calc.length?Math.round(verified/calc.length*100):0,methodologyNote:'Aggregated from current calculation records. Public values are a publication snapshot, not an assurance opinion.'},
  esg:{approvedIndicators:approved.length,averageScore:score,compliantIndicators:compliant,complianceShare:approved.length?Math.round(compliant/approved.length*100):0,note:'Includes only organization-approved ESG indicators.'},
  targets:(targets.data??[]).map(row=>({...row,progressPercent:row.current_value===null?null:Math.max(0,Math.min(100,Math.round((n(row.baseline_value)-n(row.current_value))/Math.max(.000001,n(row.baseline_value)-n(row.target_value))*100)))})),
  pathways:pathways.data??[],suppliers:aggregateSupplierReadiness(suppliers.data??[]),
  assets:assets.map(({asset_type,title,summary,display_order}:any)=>({type:asset_type,title,summary,displayOrder:display_order})),
  commitments:cleanItems(content.commitments),policies:cleanItems(content.policies),certificates:cleanItems(content.certificates),
  disclosures:{boundary:'Published organization-level aggregates and explicitly selected content only.',limitation:'Values may be unaudited unless a specific assurance statement is published.',contact:str(content.contact).slice(0,240)}
 };
}

export function createPublicPortalRouter(){const router=Router();
 router.get('/public/portals/:slug',async(req,res)=>{const slug=normalizePortalSlug(req.params.slug),{data,error}=await supabaseAdmin.from('public_esg_portals').select('published_snapshot,status').eq('slug',slug).eq('status','published').single();if(error||!data?.published_snapshot)return res.status(404).json({error:'Public ESG portal not found.'});res.set('Cache-Control','public, max-age=300, stale-while-revalidate=600');res.json({data:data.published_snapshot});});
 router.get('/portal/admin',requireAuth,requirePermission('public_portal.view'),requireEntitlement('public.portal'),async(req:AuthenticatedRequest,res)=>{try{const org=req.authorization!.organisationId,[portalResult,available]=await Promise.all([supabaseAdmin.from('public_esg_portals').select('*').eq('organisation_id',org).maybeSingle(),sources(org)]);if(portalResult.error)throw new Error(portalResult.error.message);let assets:any[]=[];if(portalResult.data){const result=await supabaseAdmin.from('public_portal_assets').select('*').eq('portal_id',portalResult.data.id).eq('organisation_id',org).order('display_order');if(result.error)throw new Error(result.error.message);assets=result.data??[]}res.json({portal:portalResult.data,assets,sources:available});}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Unable to load portal administration.'});}});
 router.put('/portal/admin',requireAuth,requireOperationalLicense,requirePermission('public_portal.manage'),requireEntitlement('public.portal'),async(req:AuthenticatedRequest,res)=>{try{const org=req.authorization!.organisationId,b=req.body??{},slug=normalizePortalSlug(b.slug),sections=validPortalSections(b.enabledSections);if(!slug||!str(b.title)||!sections.length)return res.status(400).json({error:'Title, valid slug, and at least one section are required.'});const content={commitments:cleanItems(b.content?.commitments),policies:cleanItems(b.content?.policies),certificates:cleanItems(b.content?.certificates),contact:str(b.content?.contact).slice(0,240)};const row={id:str(b.id)||`public-portal-${randomUUID()}`,organisation_id:org,slug,title:str(b.title),summary:str(b.summary).slice(0,1200),enabled_sections:sections,content,theme:{primaryColor:str(b.theme?.primaryColor)||'#173f2a',accentColor:str(b.theme?.accentColor)||'#d39b35'}};const {data,error}=await supabaseAdmin.from('public_esg_portals').upsert(row,{onConflict:'organisation_id'}).select('*').single();if(error)throw new Error(error.message);res.json({portal:data});}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Unable to save portal.'});}});
 router.put('/portal/admin/assets',requireAuth,requireOperationalLicense,requirePermission('public_portal.manage'),requireEntitlement('public.portal'),async(req:AuthenticatedRequest,res)=>{try{const org=req.authorization!.organisationId,{data:portal}=await supabaseAdmin.from('public_esg_portals').select('id').eq('organisation_id',org).single();if(!portal)return res.status(400).json({error:'Save portal settings first.'});const requested=Array.isArray(req.body?.assets)?req.body.assets.slice(0,40):[],available=await sources(org),entries:Array<[string,{type:string;title:string;summary:string}]>=[...available.reports.map((x:any)=>[x.id,{type:'report',title:x.title,summary:x.summary??''}] as [string,{type:string;title:string;summary:string}]),...available.documents.map((x:any)=>[x.id,{type:'document',title:x.name,summary:`${x.category} · ${x.period}`}] as [string,{type:string;title:string;summary:string}])],allowed=new Map(entries);const rows=requested.map((item:any,index:number)=>{const source=allowed.get(str(item.assetId));return source?{id:`public-asset-${randomUUID()}`,organisation_id:org,portal_id:portal.id,asset_type:source.type,asset_id:str(item.assetId),title:source.title,summary:source.summary,display_order:index,created_by:req.authUser!.id}:null}).filter(Boolean);await supabaseAdmin.from('public_portal_assets').delete().eq('portal_id',portal.id).eq('organisation_id',org);if(rows.length){const inserted=await supabaseAdmin.from('public_portal_assets').insert(rows);if(inserted.error)throw new Error(inserted.error.message)}res.json({count:rows.length});}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Unable to update portal assets.'});}});
 router.post('/portal/admin/publish',requireAuth,requireOperationalLicense,requirePermission('public_portal.publish'),requireEntitlement('public.portal'),async(req:AuthenticatedRequest,res)=>{try{const org=req.authorization!.organisationId,{data:portal,error}=await supabaseAdmin.from('public_esg_portals').select('*').eq('organisation_id',org).single();if(error||!portal)return res.status(400).json({error:'Configure the portal before publishing.'});const {data:assets}=await supabaseAdmin.from('public_portal_assets').select('*').eq('portal_id',portal.id).eq('organisation_id',org).order('display_order'),snapshot=await buildSnapshot(org,portal,assets??[]),readiness=publicationReadiness({title:portal.title,slug:portal.slug,sections:portal.enabled_sections,snapshot});if(!readiness.ready)return res.status(400).json({error:'Portal is not publication-ready.',issues:readiness.issues});const version=n(portal.snapshot_version)+1;const history=await supabaseAdmin.from('public_portal_publications').insert({id:`public-publication-${randomUUID()}`,organisation_id:org,portal_id:portal.id,version,snapshot,change_summary:str(req.body?.changeSummary),published_by:req.authUser!.id});if(history.error)throw new Error(history.error.message);const {data,error:updateError}=await supabaseAdmin.from('public_esg_portals').update({status:'published',published_snapshot:snapshot,snapshot_version:version,published_at:new Date().toISOString(),published_by:req.authUser!.id}).eq('id',portal.id).eq('organisation_id',org).select('*').single();if(updateError)throw new Error(updateError.message);res.json({portal:data,publicPath:`/portal/${portal.slug}`,version});}catch(e){res.status(500).json({error:e instanceof Error?e.message:'Unable to publish portal.'});}});
 router.post('/portal/admin/unpublish',requireAuth,requireOperationalLicense,requirePermission('public_portal.publish'),requireEntitlement('public.portal'),async(req:AuthenticatedRequest,res)=>{const {data,error}=await supabaseAdmin.from('public_esg_portals').update({status:'unpublished'}).eq('organisation_id',req.authorization!.organisationId).select('*').single();if(error)return res.status(500).json({error:error.message});res.json({portal:data});});
 return router;}
