import { evaluateAnalyticsFormula } from './analyticsFormula.js';
import { linearProjection } from './analyticsProjection.js';
import { supabaseAdmin } from './supabaseClients.js';

export type AnalyticsFilters = { dateFrom?: string; dateTo?: string; facilityIds?: string[]; scopes?: string[]; sources?: string[] };
export type KpiDefinition = { key: string; name: string; formula: string; unit: string; format: string; direction: string; category?: string };

const finite = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const month = (value: unknown) => String(value ?? '').slice(0, 7) || 'Unassigned';
const tonneUnit = (value: unknown) => ['t','ton','tonne','tonnes','metric tonne','metric tonnes'].includes(String(value ?? '').trim().toLowerCase());

export async function buildAnalyticsDataset(organisationId: string, filters: AnalyticsFilters, definitions: KpiDefinition[]) {
  let calculationQuery = supabaseAdmin.from('calculation_records').select('id,emissions_t_co2e,factor_version,calculated_at,activity_records!inner(id,facility_id,scope,source_type,activity_category,activity_date,quantity,unit,verification_status,facilities(id,name,location),activity_evidence_links(id))').eq('organisation_id', organisationId).eq('status', 'current').is('activity_records.deleted_at', null);
  if (filters.dateFrom) calculationQuery = calculationQuery.gte('activity_records.activity_date', filters.dateFrom);
  if (filters.dateTo) calculationQuery = calculationQuery.lte('activity_records.activity_date', filters.dateTo);
  if (filters.facilityIds?.length) calculationQuery = calculationQuery.in('activity_records.facility_id', filters.facilityIds);
  if (filters.scopes?.length) calculationQuery = calculationQuery.in('activity_records.scope', filters.scopes);
  if (filters.sources?.length) calculationQuery = calculationQuery.in('activity_records.source_type', filters.sources);
  let productionQuery = supabaseAdmin.from('production_records').select('id,facility_id,date,quantity,unit').eq('organisation_id', organisationId);
  if (filters.dateFrom) productionQuery = productionQuery.gte('date', filters.dateFrom); if (filters.dateTo) productionQuery = productionQuery.lte('date', filters.dateTo); if (filters.facilityIds?.length) productionQuery = productionQuery.in('facility_id', filters.facilityIds);
  const [calculationResult, productionResult, facilitiesResult, projectsResult, scenariosResult] = await Promise.all([
    calculationQuery, productionQuery, supabaseAdmin.from('facilities').select('id,name,location').eq('organisation_id', organisationId).is('deleted_at', null),
    supabaseAdmin.from('decarbonization_projects').select('id,status,target_annual_reduction_t_co2e').eq('organisation_id', organisationId),
    supabaseAdmin.from('reduction_scenarios').select('id,title,facility_id,scenario_type,baseline_emissions_t_co2e,scenario_emissions_t_co2e,estimated_reduction_t_co2e,estimated_reduction_percent,created_at').eq('organisation_id', organisationId).order('created_at',{ascending:false}).limit(20),
  ]);
  const error = calculationResult.error ?? productionResult.error ?? facilitiesResult.error ?? projectsResult.error ?? scenariosResult.error; if (error) throw new Error(error.message);
  const calculations = (calculationResult.data ?? []).map((row: any) => ({ ...row, activity: row.activity_records }));
  const production = (productionResult.data ?? []).filter((row: any) => tonneUnit(row.unit)); const facilities = facilitiesResult.data ?? [];
  const emissionsTotal = calculations.reduce((sum, row) => sum + finite(row.emissions_t_co2e), 0), scope1Total = calculations.filter((row) => row.activity.scope === 'scope-1').reduce((sum, row) => sum + finite(row.emissions_t_co2e), 0), scope2Total = calculations.filter((row) => row.activity.scope === 'scope-2').reduce((sum, row) => sum + finite(row.emissions_t_co2e), 0);
  const productionTotal = production.reduce((sum: number, row: any) => sum + finite(row.quantity), 0), scope2Quantity = calculations.filter((row) => row.activity.scope === 'scope-2').reduce((sum, row) => sum + finite(row.activity.quantity), 0), renewableQuantity = calculations.filter((row) => /renewable|solar|wind/i.test(`${row.activity.activity_category} ${row.activity.source_type}`)).reduce((sum, row) => sum + finite(row.activity.quantity), 0);
  const activitiesWithEvidence = calculations.filter((row) => (row.activity.activity_evidence_links ?? []).length > 0).length, approvedActivityCount = calculations.filter((row) => ['approved','verified'].includes(row.activity.verification_status)).length;
  const variables = { emissions_total: emissionsTotal, scope1_total: scope1Total, scope2_total: scope2Total, production_total: productionTotal, scope2_quantity: scope2Quantity, renewable_quantity: renewableQuantity, activity_count: calculations.length, activities_with_evidence: activitiesWithEvidence, approved_activity_count: approvedActivityCount, facility_count: facilities.length, project_count: projectsResult.data?.length ?? 0, planned_reduction: (projectsResult.data ?? []).reduce((sum: number, row: any) => sum + finite(row.target_annual_reduction_t_co2e), 0) };
  const kpis = definitions.map((definition) => ({ ...definition, value: evaluateAnalyticsFormula(definition.formula, variables) }));
  const aggregate = (dimension: 'month'|'facility'|'scope'|'source') => { const grouped = new Map<string, { key: string; name: string; emissions: number; scope1: number; scope2: number; records: number }>(); calculations.forEach((row) => { const key = dimension === 'month' ? month(row.activity.activity_date) : dimension === 'facility' ? row.activity.facility_id : dimension === 'scope' ? row.activity.scope : row.activity.source_type || 'Unknown'; const name = dimension === 'facility' ? row.activity.facilities?.name ?? key : key; const value = grouped.get(key) ?? { key, name, emissions: 0, scope1: 0, scope2: 0, records: 0 }; value.emissions += finite(row.emissions_t_co2e); value.records += 1; if (row.activity.scope === 'scope-1') value.scope1 += finite(row.emissions_t_co2e); if (row.activity.scope === 'scope-2') value.scope2 += finite(row.emissions_t_co2e); grouped.set(key, value); }); return [...grouped.values()].sort((a, b) => dimension === 'month' ? a.key.localeCompare(b.key) : b.emissions - a.emissions); };
  const monthly = aggregate('month'), byFacility = aggregate('facility').map((row) => { const output = production.filter((item: any) => item.facility_id === row.key).reduce((sum: number, item: any) => sum + finite(item.quantity), 0); return { ...row, production: output, intensity: output ? row.emissions * 1000 / output : null }; }), bySource = aggregate('source'), byScope = aggregate('scope');
  const facilityValues = byFacility.map((row) => row.intensity).filter((value): value is number => value !== null).sort((a,b) => a-b), median = facilityValues.length ? facilityValues[Math.floor(facilityValues.length / 2)] : null;
  const previous=monthly.at(-2),current=monthly.at(-1),largestSource=bySource[0],highestIntensity=[...byFacility].filter(row=>row.intensity!==null).sort((a,b)=>finite(b.intensity)-finite(a.intensity))[0];
  const insights = [
    previous&&current&&previous.emissions>0?{type:'period-change',severity:Math.abs((current.emissions-previous.emissions)/previous.emissions)>0.2?'attention':'information',text:`Recorded emissions changed ${(((current.emissions-previous.emissions)/previous.emissions)*100).toFixed(1)}% from ${previous.key} to ${current.key}.`,basis:[previous.key,current.key]}:{type:'data-requirement',severity:'information',text:'At least two monthly observations are required for a period comparison.',basis:[]},
    largestSource?{type:'source-concentration',severity:largestSource.emissions>emissionsTotal*0.6?'attention':'information',text:`${largestSource.name} contributes ${emissionsTotal?((largestSource.emissions/emissionsTotal)*100).toFixed(1):'0.0'}% of filtered emissions.`,basis:[largestSource.key]}:{type:'data-requirement',severity:'information',text:'No calculated source contribution is available for the selected filters.',basis:[]},
    highestIntensity&&median?{type:'facility-benchmark',severity:highestIntensity.intensity!>median*1.25?'attention':'information',text:`${highestIntensity.name} has the highest recorded intensity at ${highestIntensity.intensity!.toFixed(1)} kgCO2e/t versus the internal median of ${median.toFixed(1)}.`,basis:[highestIntensity.key]}:{type:'data-requirement',severity:'information',text:'Compatible production output is required for facility intensity benchmarking.',basis:[]},
  ];
  return { generatedAt: new Date().toISOString(), filters, kpis, variables, series: { monthly, facility: byFacility, source: bySource, scope: byScope }, forecast: linearProjection(monthly.map((row) => ({ period: row.key, value: row.emissions }))), benchmark: { type: 'internal-facility-median', metric: 'carbon_intensity', median, note:'No external industry benchmark is inferred.', facilities: byFacility.map((row) => ({ facilityId: row.key, name: row.name, value: row.intensity, variancePercent: median && row.intensity !== null ? (row.intensity - median) / median * 100 : null })) }, scenarioComparison:(scenariosResult.data??[]).map((row:any)=>({id:row.id,title:row.title,facilityId:row.facility_id,type:row.scenario_type,baseline:finite(row.baseline_emissions_t_co2e),scenario:finite(row.scenario_emissions_t_co2e),reduction:finite(row.estimated_reduction_t_co2e),reductionPercent:finite(row.estimated_reduction_percent),createdAt:row.created_at})), insights, drillRows: calculations.slice(0, 500).map((row) => ({ calculationId: row.id, activityId: row.activity.id, date: row.activity.activity_date, facilityId: row.activity.facility_id, facility: row.activity.facilities?.name, scope: row.activity.scope, source: row.activity.source_type, quantity: row.activity.quantity, unit: row.activity.unit, emissionsTco2e: finite(row.emissions_t_co2e), status: row.activity.verification_status, factorVersion: row.factor_version, evidenceCount: (row.activity.activity_evidence_links ?? []).length })) };
}
