import { randomUUID } from 'node:crypto';
import { calculateActivityEmissions, deriveActivityType } from './carbonAccounting.js';
import { resolveRegistryFactor, saveCalculationLineage } from './carbonLedgerService.js';
import { refreshFacilityAggregates } from './facilityAggregates.js';
import { convertActivityMeasurement, convertMeasurement, resolveUnit } from './measurementService.js';
import { str } from './requestUtils.js';
import { supabaseAdmin } from './supabaseClients.js';

async function facilityFor(organisationId: string, facilityId: string) {
  const { data, error } = await supabaseAdmin.from('facilities').select('*').eq('id', facilityId).eq('organisation_id', organisationId).maybeSingle();
  if (error || !data) throw new Error(error?.message ?? `Facility ${facilityId} was not found in this organisation.`); return data;
}

export async function postStagedRecord(input: { organisationId: string; userId: string; stagedRecord: any }) {
  const data = input.stagedRecord.canonical_data ?? {}; const target = input.stagedRecord.target_entity_key;
  if (target === 'activity') return postEnergy(input.organisationId, input.userId, input.stagedRecord.id, data);
  if (target === 'production') return postProduction(input.organisationId, input.userId, input.stagedRecord.id, data);
  if (target === 'water') return postEnvironmental(input.organisationId, input.userId, input.stagedRecord.id, data, 'water');
  if (target === 'waste') return postEnvironmental(input.organisationId, input.userId, input.stagedRecord.id, data, 'waste');
  if (target === 'material') return postEnvironmental(input.organisationId, input.userId, input.stagedRecord.id, data, 'material');
  if (target === 'air-emission') return postAirEmission(input.organisationId, input.userId, input.stagedRecord.id, data);
  throw new Error(`Operational posting for ${target} is not configured yet. Keep this record approved in staging.`);
}

async function postEnvironmental(organisationId: string, userId: string, stagedId: string, data: any, kind: 'water' | 'waste' | 'material') {
  const facilityId = str(data.facility_id); const quantity = Number(data.quantity); const unit = str(data.unit); if (!facilityId || !Number.isFinite(quantity) || quantity < 0 || !unit) throw new Error('Facility, quantity, and unit are required.'); await facilityFor(organisationId, facilityId); const inputUnit = await resolveUnit(unit); if (!inputUnit) throw new Error(`${unit} is not registered.`); const canonicalUnit = kind === 'water' ? 'water-m3' : inputUnit.category_id === 'unitcat-mass' ? 'kg' : inputUnit.category_id === 'unitcat-water' ? 'water-m3' : 'm3'; const converted = await convertMeasurement({ value: quantity, fromUnit: unit, toUnit: canonicalUnit, organisationId, userId, context: `${kind}-import`, audit: true }); const common = { id: `${kind}-${randomUUID()}`, organisation_id: organisationId, facility_id: facilityId, date: str(data.date) || new Date().toISOString().slice(0,10), reporting_period: str(data.reporting_period), quantity, unit, input_quantity: quantity, input_unit: converted.fromUnit, canonical_quantity: converted.canonicalValue, canonical_unit: converted.canonicalUnit, conversion_factor: converted.conversionFactor, conversion_path: converted.conversionPath, source_document: str(data.source_document), notes: str(data.notes), staged_record_id: stagedId, created_by: userId };
  const specific = kind === 'water' ? { flow_type: str(data.flow_type), source: str(data.source), destination: str(data.destination), quality_parameter: str(data.quality_parameter) } : kind === 'waste' ? { waste_type: str(data.waste_type), disposal_method: str(data.disposal_method), recovery_method: str(data.recovery_method), vendor: str(data.vendor) } : { material: str(data.material), supplier: str(data.supplier), batch: str(data.batch), origin: str(data.origin), recycled_content: data.recycled_content === '' || data.recycled_content === undefined ? null : Number(data.recycled_content) };
  const table = kind === 'water' ? 'water_records' : kind === 'waste' ? 'waste_records' : 'material_records'; const { data: record, error } = await supabaseAdmin.from(table).insert({ ...common, ...specific }).select('id').single(); if (error || !record) throw new Error(error?.message ?? `Unable to post ${kind} record.`); return { target: table, recordId: record.id };
}

async function postAirEmission(organisationId: string, userId: string, stagedId: string, data: any) {
  const facilityId = str(data.facility_id); const value = Number(data.value); if (!facilityId || !str(data.parameter) || !Number.isFinite(value) || value < 0 || !str(data.unit)) throw new Error('Facility, parameter, value, and unit are required.'); await facilityFor(organisationId, facilityId); const { data: record, error } = await supabaseAdmin.from('air_emission_records').insert({ id: `air-${randomUUID()}`, organisation_id: organisationId, facility_id: facilityId, date: str(data.date) || new Date().toISOString().slice(0,10), reporting_period: str(data.reporting_period), parameter: str(data.parameter), value, unit: str(data.unit), stack_id: str(data.stack_id), method: str(data.method), regulatory_limit: data.limit === '' || data.limit === undefined ? null : Number(data.limit), source_document: str(data.source_document), notes: str(data.notes), staged_record_id: stagedId, created_by: userId }).select('id').single(); if (error || !record) throw new Error(error?.message ?? 'Unable to post air-emission record.'); return { target: 'air_emission_records', recordId: record.id };
}

async function postEnergy(organisationId: string, userId: string, stagedId: string, data: any) {
  const facilityId = str(data.facility_id); const sourceType = str(data.source_type); const quantity = Number(data.quantity); const unit = str(data.unit); const sourceDocument = str(data.source_document);
  if (!facilityId || !sourceType || !Number.isFinite(quantity) || quantity < 0 || !unit) throw new Error('Facility, source type, quantity, and unit are required for energy posting.');
  const facility = await facilityFor(organisationId, facilityId); const activityDate = str(data.date) || new Date().toISOString().slice(0, 10); const factor = await resolveRegistryFactor(sourceType, facility.country || 'India', activityDate); if (!factor) throw new Error(`No active emission factor found for ${sourceType}.`);
  const converted = await convertActivityMeasurement({ quantity, inputUnit: unit, factorUnit: factor.activityUnit, sourceType, organisationId, userId }); const calculation = calculateActivityEmissions({ quantity: converted.factorValue, activityUnit: factor.activityUnit, sourceType, emissionFactor: factor });
  const metadata = { methodology: 'activity_data_x_emission_factor', importSource: 'enterprise-data-platform', stagedRecordId: stagedId, emissionFactorId: factor.id, factorVersion: factor.version };
  const row = { id: `rec-${randomUUID()}`, organisation_id: organisationId, facility_id: facilityId, date: activityDate, reporting_period: str(data.reporting_period) || facility.reporting_period || new Date().getFullYear().toString(), activity_type: deriveActivityType(sourceType), source_type: sourceType, energy_type: sourceType, quantity: converted.factorValue, unit: calculation.normalizedUnit, scope: factor.scope, input_quantity: converted.inputValue, input_unit: converted.inputUnit, canonical_quantity: converted.canonicalValue, canonical_unit: converted.canonicalUnit, conversion_factor: converted.conversionFactor, conversion_path: converted.conversionPath, emission_factor_id: calculation.emissionFactorId, emission_factor_value: calculation.emissionFactorValue, emission_factor_unit: calculation.emissionFactorUnit, emissions_kg_co2e: calculation.emissionsKgCO2e, emissions_t_co2e: calculation.emissionsTCO2e, source_document: sourceDocument, notes: str(data.notes), emissions: calculation.emissionsTCO2e, audit_trail: metadata, calculation_metadata: metadata };
  (row as any).emission_factor_id = null; (row as any).registry_emission_factor_id = calculation.emissionFactorId;
  const { data: record, error } = await supabaseAdmin.from('energy_records').insert(row).select('*').single(); if (error || !record) throw new Error(error?.message ?? 'Unable to post energy record.');
  const lineage = await saveCalculationLineage({ organisationId, userId, legacyEnergyRecordId: record.id, facilityId, sourceType, activityDate, reportingPeriod: row.reporting_period, quantity: converted.factorValue, unit: row.unit, supplier: str(data.supplier), invoiceNumber: str(data.invoice_number), cost: data.cost === '' || data.cost === undefined ? null : Number(data.cost), currency: str(data.currency) || 'INR', sourceDocument, notes: row.notes, factor, calculation, inputQuantity: converted.inputValue, inputUnit: converted.inputUnit, canonicalQuantity: converted.canonicalValue, canonicalUnit: converted.canonicalUnit, conversionFactor: converted.conversionFactor, conversionPath: converted.conversionPath });
  await refreshFacilityAggregates(organisationId, facilityId); return { target: 'energy_records', recordId: record.id, activityId: lineage.activity.id, calculationId: lineage.calculationRecord.id };
}

async function postProduction(organisationId: string, userId: string, stagedId: string, data: any) {
  const facilityId = str(data.facility_id); const quantity = Number(data.quantity); const unit = str(data.unit); if (!facilityId || !Number.isFinite(quantity) || quantity < 0 || !unit) throw new Error('Facility, quantity, and unit are required for production posting.'); await facilityFor(organisationId, facilityId);
  const inputUnit = await resolveUnit(unit); if (!inputUnit || !['unitcat-production', 'unitcat-mass', 'unitcat-count'].includes(inputUnit.category_id)) throw new Error(`${unit} is not a valid production unit.`); const canonicalUnit = inputUnit.category_id === 'unitcat-mass' ? 'kg' : inputUnit.category_id === 'unitcat-count' ? inputUnit.code : 'production-kg'; const converted = await convertMeasurement({ value: quantity, fromUnit: unit, toUnit: canonicalUnit, organisationId, userId, context: 'data-platform-posting', audit: true });
  const row = { id: `prod-${randomUUID()}`, organisation_id: organisationId, facility_id: facilityId, date: str(data.date) || new Date().toISOString().slice(0, 10), reporting_period: str(data.reporting_period) || 'Current period', quantity, unit, input_quantity: quantity, input_unit: converted.fromUnit, canonical_quantity: converted.canonicalValue, canonical_unit: converted.canonicalUnit, conversion_factor: converted.conversionFactor, conversion_path: converted.conversionPath, source_document: str(data.source_document), notes: `${str(data.notes)} Imported from staged record ${stagedId}.`.trim() };
  const { data: record, error } = await supabaseAdmin.from('production_records').insert(row).select('*').single(); if (error || !record) throw new Error(error?.message ?? 'Unable to post production record.'); const { data: activity, error: activityError } = await supabaseAdmin.from('activity_records').insert({ id: `activity-production-${randomUUID()}`, organisation_id: organisationId, facility_id: facilityId, activity_category: 'production', source_type: 'Production Output', activity_date: row.date, reporting_period: row.reporting_period, quantity, unit, input_quantity: quantity, input_unit: converted.fromUnit, canonical_quantity: converted.canonicalValue, canonical_unit: converted.canonicalUnit, conversion_factor: converted.conversionFactor, conversion_path: converted.conversionPath, source_document: row.source_document, notes: row.notes, verification_status: row.source_document ? 'submitted' : 'draft', created_by: userId, updated_by: userId }).select('id').single(); if (activityError || !activity) throw new Error(activityError?.message ?? 'Unable to create production lineage.'); return { target: 'production_records', recordId: record.id, activityId: activity.id };
}
