import { useEffect, useMemo, useState } from 'react';
import { Bookmark, Bot, Calculator, Check, ChevronDown, ChevronUp, Download, Eye, Filter, GripVertical, LayoutDashboard, LoaderCircle, Plus, Save, Trash2, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

import { useAuth } from '../contexts/AuthContext.tsx';
import { getAuthenticatedHeaders, safeFetchJson } from '../services/apiClient.ts';

type Filters = { dateFrom?: string; dateTo?: string; facilityIds?: string[]; scopes?: string[]; sources?: string[] };
type Kpi = { id: string; key: string; name: string; description: string; category: string; formula: string; unit: string; format: string; direction: string; value?: number };
type Widget = { id: string; title: string; widget_type: string; kpi_key: string; dimension: string; grid_w: number; grid_h: number; position: number; configuration?: any };
type Dashboard = { id: string; name: string; description: string; dashboard_type: string; visibility: string; status: string; virtual?: boolean; analytics_widgets: Widget[] };
type Catalog = { kpis: Kpi[]; dashboards: Dashboard[]; savedViews: Array<{ id: string; name: string; filters: Filters }>; bookmarks: Array<{ id: string; name: string; dashboard_id: string; state: any }>; facilities: Array<{ id: string; name: string; location: string }>; features?: { studio: boolean; forecasting: boolean } };

const colors = ['#1F5A3D','#3F7D58','#C88A32','#55738f','#8a6552','#6f7c70'];
const normalizedWidgets = (dashboard?: Dashboard | null) => [...(dashboard?.analytics_widgets ?? [])].sort((a,b) => Number(a.position)-Number(b.position)).map((widget,index)=>({ ...widget, position:index, grid_w:Number(widget.grid_w??4), grid_h:Number(widget.grid_h??3) }));
const formatValue = (value: unknown, format: string) => { const number = Number(value ?? 0); if (format === 'percent') return `${number.toFixed(1)}%`; if (format === 'currency') return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(number); return number.toLocaleString('en-IN',{maximumFractionDigits:2}); };

export default function AnalyticsStudio() {
  const { can } = useAuth(); const [catalog,setCatalog]=useState<Catalog|null>(null); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [widgets,setWidgets]=useState<Widget[]>([]); const [data,setData]=useState<any>(null); const [filters,setFilters]=useState<Filters>({scopes:['scope-1','scope-2']}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [editing,setEditing]=useState(false); const [message,setMessage]=useState(''); const [drill,setDrill]=useState<{dimension:string;key:string;title:string}|null>(null); const [savedName,setSavedName]=useState('');
  const [widgetForm,setWidgetForm]=useState({title:'New metric',widgetType:'kpi',kpiKey:'emissions_total',dimension:'month'}); const [kpiForm,setKpiForm]=useState({key:'',name:'',formula:'',unit:'',format:'decimal'}); const [aiExplanation,setAiExplanation]=useState<any>(null);
  const editable=can('analytics.edit')&&Boolean(catalog?.features?.studio); const resultKpis = useMemo(() => new Map((data?.kpis??[]).map((item:any)=>[item.key,item])),[data]);
  const load=async()=>{setLoading(true);const next=await safeFetchJson('/api/analytics/catalog',undefined,null);if(next?.dashboards){setCatalog(next);const selected=next.dashboards[0];setDashboard(selected);setWidgets(normalizedWidgets(selected));}else setMessage('Analytics schema is not available. Run migration 026.');setLoading(false);};
  const query=async(nextFilters=filters)=>{setBusy(true);const response=await safeFetchJson('/api/analytics/query',{method:'POST',body:JSON.stringify({filters:nextFilters})},null);if(response?.data)setData(response.data);else setMessage('Analytics query failed. Check plan access and current calculation records.');setBusy(false);};
  useEffect(()=>{void load();},[]); useEffect(()=>{if(catalog)void query();},[catalog]);
  const selectDashboard=(next:Dashboard)=>{setDashboard(next);setWidgets(normalizedWidgets(next));setEditing(false);};
  const moveWidget=(id:string,delta:number)=>{const rows=[...widgets],index=rows.findIndex(item=>item.id===id),target=index+delta;if(target<0||target>=rows.length)return;[rows[index],rows[target]]=[rows[target],rows[index]];setWidgets(rows.map((item,position)=>({...item,position})));};
  const addWidget=()=>{const item:Widget={id:`local-${crypto.randomUUID()}`,title:widgetForm.title,widget_type:widgetForm.widgetType,kpi_key:widgetForm.kpiKey,dimension:widgetForm.widgetType==='kpi'?'':widgetForm.dimension,grid_w:widgetForm.widgetType==='kpi'?3:widgetForm.widgetType==='table'?8:6,grid_h:widgetForm.widgetType==='kpi'?2:4,position:widgets.length,configuration:{}};setWidgets(rows=>[...rows,item]);};
  const saveDashboard=async()=>{if(!dashboard)return;setBusy(true);let target=dashboard;if(dashboard.virtual){const created=await safeFetchJson('/api/analytics/dashboards',{method:'POST',body:JSON.stringify({name:`${dashboard.name} - Custom`,description:dashboard.description,dashboardType:'executive',visibility:'private',filters})},null);if(!created?.dashboard){setMessage('Could not create a persisted dashboard.');setBusy(false);return;}target={...created.dashboard,analytics_widgets:[]};}
    const response=await safeFetchJson(`/api/analytics/dashboards/${target.id}`,{method:'PUT',body:JSON.stringify({name:target.name,description:target.description,visibility:target.visibility,status:'draft',filters,widgets})},null);if(response?.dashboard){setDashboard(response.dashboard);setWidgets(normalizedWidgets(response.dashboard));setEditing(false);setMessage('Dashboard layout saved.');await load();}else setMessage('Dashboard save failed.');setBusy(false);};
  const createKpi=async()=>{setBusy(true);const response=await safeFetchJson('/api/analytics/kpis',{method:'POST',body:JSON.stringify(kpiForm)},null);if(response?.kpi){setMessage('Custom KPI created.');setKpiForm({key:'',name:'',formula:'',unit:'',format:'decimal'});await load();}else setMessage('KPI formula was rejected. Use allow-listed base variables and arithmetic operators only.');setBusy(false);};
  const saveView=async()=>{if(!savedName)return;const response=await safeFetchJson('/api/analytics/saved-views',{method:'POST',body:JSON.stringify({name:savedName,filters})},null);if(response?.savedView){setSavedName('');setMessage('Filter view saved.');await load();}};
  const bookmark=async()=>{if(!dashboard||dashboard.virtual){setMessage('Save the dashboard before creating a bookmark.');return;}const response=await safeFetchJson('/api/analytics/bookmarks',{method:'POST',body:JSON.stringify({dashboardId:dashboard.id,name:`${dashboard.name} ${new Date().toLocaleDateString()}`,state:{filters,drill}})},null);if(response?.bookmark){setMessage('Dashboard state bookmarked.');await load();}};
  const exportData=async(format:'csv'|'json')=>{if(!dashboard)return;setBusy(true);try{const response=await fetch('/api/analytics/export',{method:'POST',headers:{...getAuthenticatedHeaders(),'Content-Type':'application/json'},body:JSON.stringify({format,dashboardId:dashboard.virtual?null:dashboard.id,filters})});const payload=await response.json();if(!response.ok||!payload?.export?.contentBase64)throw new Error(payload?.error||'Export failed.');const raw=atob(payload.export.contentBase64),bytes=Uint8Array.from(raw,char=>char.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:payload.export.mimeType}));const anchor=document.createElement('a');anchor.href=url;anchor.download=payload.export.filename;anchor.click();URL.revokeObjectURL(url);setMessage(`${format.toUpperCase()} export created.`);}catch(error){setMessage(error instanceof Error?error.message:'Export failed.');}setBusy(false);};
  const crossFilter=(dimension:string,key:string)=>{const next={...filters};if(dimension==='facility')next.facilityIds=[key];if(dimension==='scope')next.scopes=[key];if(dimension==='source')next.sources=[key];setFilters(next);void query(next);};
  const explain=async()=>{setBusy(true);const response=await safeFetchJson('/api/analytics/explain',{method:'POST',body:JSON.stringify({filters})},null);setAiExplanation(response?.explanation??null);setMessage(response?.explanation?'Carbon Copilot explanation generated from filtered aggregates.':'AI explanation is unavailable. Check local Ollama and plan access.');setBusy(false);};
  if(loading)return <div className="min-h-72 flex items-center justify-center text-xs text-gray-500"><LoaderCircle className="w-5 h-5 animate-spin mr-2"/>Loading Analytics Studio...</div>;
  return <div className="space-y-4 min-w-0">
    <header className="bg-brand-charcoal text-white rounded-lg p-5 flex flex-col xl:flex-row xl:items-center xl:justify-between gap-4"><div><p className="text-[10px] font-mono uppercase text-brand-sage">Formal Phase 10 | Enterprise Analytics</p><h1 className="text-xl font-black mt-1">Governed carbon analytics studio</h1><p className="text-xs text-gray-300 mt-1">Build views from current calculation lineage, not duplicated dashboard totals.</p></div><div className="flex flex-wrap gap-2">{editable&&<button onClick={()=>setEditing(value=>!value)} className="studio-action"><LayoutDashboard className="w-4 h-4"/>{editing?'Preview':'Edit layout'}</button>}{editing&&<button onClick={saveDashboard} disabled={busy} className="studio-action"><Save className="w-4 h-4"/>Save</button>}<button onClick={bookmark} className="studio-icon-action" title="Bookmark state"><Bookmark/></button><button onClick={()=>void exportData('csv')} className="studio-icon-action" title="Export CSV"><Download/></button></div></header>
    {message&&<div className="bg-white border border-brand-border rounded px-4 py-2 text-xs text-brand-forest flex gap-2"><Check className="w-4 h-4"/>{message}</div>}
    <section className="bg-white border border-brand-border rounded-lg p-4 flex flex-col lg:flex-row lg:items-center gap-3"><div className="flex-1"><h2 className="text-xs font-black flex items-center gap-1.5"><Bot className="w-4 h-4 text-brand-forest"/>Carbon Copilot analytics explanation</h2><p className="text-[10px] text-gray-500 mt-1">Read-only narrative from filtered KPI aggregates. Deterministic calculations remain authoritative.</p></div><button onClick={explain} disabled={busy} className="studio-secondary">Explain this view</button>{aiExplanation&&<button onClick={()=>setAiExplanation(null)} title="Close explanation" className="studio-mini"><X/></button>}</section>
    {aiExplanation&&<section className="bg-brand-offwhite border border-brand-border rounded-lg p-5"><p className="text-sm leading-relaxed">{aiExplanation.answer}</p><div className="flex flex-wrap gap-2 mt-3">{aiExplanation.citations?.map((item:any)=><span key={item.id} className="text-[9px] font-mono bg-white border border-brand-border px-2 py-1">{item.label}: {formatValue(item.value,'decimal')} {item.unit}</span>)}</div>{aiExplanation.limitations?.length?<p className="text-[10px] text-gray-500 mt-3">Limitations: {aiExplanation.limitations.join(' ')}</p>:null}</section>}
    <section className="bg-white border border-brand-border rounded-lg p-4"><div className="flex flex-col xl:flex-row gap-3 xl:items-end"><label className="text-[10px] font-mono text-gray-500 flex-1">DASHBOARD<select value={dashboard?.id??''} onChange={event=>{const next=catalog?.dashboards.find(item=>item.id===event.target.value);if(next)selectDashboard(next);}} className="studio-input mt-1">{catalog?.dashboards.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-[10px] font-mono text-gray-500">FROM<input type="date" value={filters.dateFrom??''} onChange={event=>setFilters(value=>({...value,dateFrom:event.target.value||undefined}))} className="studio-input mt-1"/></label><label className="text-[10px] font-mono text-gray-500">TO<input type="date" value={filters.dateTo??''} onChange={event=>setFilters(value=>({...value,dateTo:event.target.value||undefined}))} className="studio-input mt-1"/></label><label className="text-[10px] font-mono text-gray-500 min-w-48">FACILITY<select value={filters.facilityIds?.[0]??''} onChange={event=>setFilters(value=>({...value,facilityIds:event.target.value?[event.target.value]:undefined}))} className="studio-input mt-1"><option value="">All facilities</option>{catalog?.facilities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button onClick={()=>void query()} disabled={busy} className="studio-primary"><Filter className="w-4 h-4"/>Apply</button><button title="Clear filters" onClick={()=>{const next={scopes:['scope-1','scope-2']};setFilters(next);void query(next);}} className="studio-mini"><X/></button></div><div className="flex flex-wrap gap-2 mt-3"><span className="text-[10px] font-mono text-gray-400 pt-1.5">SCOPES</span>{['scope-1','scope-2'].map(scope=><button key={scope} onClick={()=>setFilters(value=>({...value,scopes:value.scopes?.includes(scope)?value.scopes.filter(item=>item!==scope):[...(value.scopes??[]),scope]}))} className={`px-3 py-1.5 rounded text-[10px] font-bold ${filters.scopes?.includes(scope)?'bg-brand-forest text-white':'bg-brand-offwhite text-gray-500'}`}>{scope.toUpperCase()}</button>)}<div className="ml-auto flex gap-2"><input value={savedName} onChange={event=>setSavedName(event.target.value)} placeholder="Saved view name" className="studio-input w-40"/><button onClick={saveView} className="studio-secondary">Save view</button>{catalog?.savedViews.map(view=><button key={view.id} onClick={()=>{setFilters(view.filters);void query(view.filters);}} className="px-2 py-1 text-[10px] bg-brand-offwhite rounded">{view.name}</button>)}</div></div></section>
    {editing&&<section className="bg-white border border-brand-border rounded-lg p-4 grid lg:grid-cols-2 gap-4"><div><h2 className="text-xs font-black">Add widget</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-2"><input value={widgetForm.title} onChange={event=>setWidgetForm(value=>({...value,title:event.target.value}))} className="studio-input"/><select value={widgetForm.widgetType} onChange={event=>setWidgetForm(value=>({...value,widgetType:event.target.value}))} className="studio-input">{['kpi','line','bar','stacked-bar','donut','table','heatmap','map','insight'].map(type=><option key={type}>{type}</option>)}</select><select value={widgetForm.kpiKey} onChange={event=>setWidgetForm(value=>({...value,kpiKey:event.target.value}))} className="studio-input">{catalog?.kpis.map(kpi=><option key={kpi.key} value={kpi.key}>{kpi.name}</option>)}</select><select value={widgetForm.dimension} onChange={event=>setWidgetForm(value=>({...value,dimension:event.target.value}))} className="studio-input">{['month','facility','source','scope','forecast'].map(item=><option key={item}>{item}</option>)}</select></div><button onClick={addWidget} className="studio-primary mt-2"><Plus className="w-4 h-4"/>Add widget</button></div><div><h2 className="text-xs font-black">Custom KPI formula</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-2"><input value={kpiForm.name} onChange={event=>setKpiForm(value=>({...value,name:event.target.value}))} placeholder="KPI name" className="studio-input"/><input value={kpiForm.key} onChange={event=>setKpiForm(value=>({...value,key:event.target.value}))} placeholder="kpi_key" className="studio-input"/><input value={kpiForm.formula} onChange={event=>setKpiForm(value=>({...value,formula:event.target.value}))} placeholder="emissions_total / facility_count" className="studio-input font-mono"/><input value={kpiForm.unit} onChange={event=>setKpiForm(value=>({...value,unit:event.target.value}))} placeholder="Unit" className="studio-input"/></div><p className="text-[9px] text-gray-400 mt-1">Allowed: base KPI variables, numbers, parentheses and + - * /. Division by zero returns zero.</p><button onClick={createKpi} disabled={!kpiForm.name||!kpiForm.key||!kpiForm.formula} className="studio-secondary mt-2"><Calculator className="w-4 h-4"/>Create KPI</button></div></section>}
    <section className="grid grid-cols-1 xl:grid-cols-12 gap-4">{widgets.map(widget=><div key={widget.id} className="bg-white border border-brand-border rounded-lg min-w-0 overflow-hidden" style={{gridColumn:`span ${Math.min(12,Math.max(3,widget.grid_w))}`}}><div className="h-11 px-4 border-b border-brand-border flex items-center justify-between"><div className="flex items-center gap-2 min-w-0">{editing&&<GripVertical className="w-4 h-4 text-gray-300"/>}<h2 className="text-xs font-black truncate">{widget.title}</h2></div>{editing?<div className="flex"><button title="Move up" onClick={()=>moveWidget(widget.id,-1)} className="studio-mini border-0"><ChevronUp/></button><button title="Move down" onClick={()=>moveWidget(widget.id,1)} className="studio-mini border-0"><ChevronDown/></button><button title="Remove widget" onClick={()=>setWidgets(rows=>rows.filter(item=>item.id!==widget.id).map((item,position)=>({...item,position})))} className="studio-mini border-0 text-red-700"><Trash2/></button></div>:<button title="Inspect records" onClick={()=>setDrill({dimension:widget.dimension,key:'',title:widget.title})} className="studio-mini border-0"><Eye/></button>}</div><div className="p-4"><WidgetView widget={widget} data={data} kpi={resultKpis.get(widget.kpi_key) as any} onFilter={crossFilter} onDrill={(key)=>setDrill({dimension:widget.dimension,key,title:widget.title})}/></div></div>)}</section>
    {drill&&<DrillDrawer drill={drill} rows={data?.drillRows??[]} onClose={()=>setDrill(null)}/>} 
  </div>;
}

function WidgetView({widget,data,kpi,onFilter,onDrill}:{widget:Widget;data:any;kpi:any;onFilter:(dimension:string,key:string)=>void;onDrill:(key:string)=>void}) {
  if(!data)return <div className="h-32 flex items-center justify-center"><LoaderCircle className="w-5 h-5 animate-spin"/></div>;
  if(widget.widget_type==='kpi')return <div className="h-24 flex flex-col justify-center"><p className="text-2xl font-black">{formatValue(kpi?.value,kpi?.format)} <span className="text-xs font-normal text-gray-400">{kpi?.unit}</span></p><p className="text-[10px] text-gray-500 mt-1">{kpi?.description||'Governed KPI'}</p></div>;
  const rows=widget.dimension==='month'?data.series.monthly:widget.dimension==='facility'?data.series.facility:widget.dimension==='scope'?data.series.scope:widget.dimension==='forecast'?data.forecast:data.series.source;
  if(widget.widget_type==='line'||widget.widget_type==='stacked-bar')return <div className="h-64"><ResponsiveContainer width="100%" height="100%">{widget.widget_type==='line'?<LineChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey={widget.dimension==='month'?'key':'name'} tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Line type="monotone" dataKey={widget.dimension==='forecast'?'value':'emissions'} stroke="#1F5A3D" strokeWidth={2}/></LineChart>:<BarChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Legend/><Bar dataKey="scope1" stackId="scope" fill="#1F5A3D"/><Bar dataKey="scope2" stackId="scope" fill="#C88A32"/></BarChart>}</ResponsiveContainer></div>;
  if(widget.widget_type==='donut')return <div className="h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="emissions" nameKey="name" innerRadius={48} outerRadius={82} onClick={(row:any)=>{onFilter(widget.dimension,row.key);onDrill(row.key);}}>{rows.map((_row:any,index:number)=><Cell key={index} fill={colors[index%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div>;
  if(widget.widget_type==='bar')return <div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" tick={{fontSize:9}}/><YAxis type="category" dataKey="name" width={90} tick={{fontSize:9}}/><Tooltip/><Bar dataKey="emissions" fill="#1F5A3D" onClick={(row:any)=>{onFilter(widget.dimension,row.key);onDrill(row.key);}}/></BarChart></ResponsiveContainer></div>;
  if(widget.widget_type==='table')return <div className="max-h-64 overflow-auto"><table className="w-full text-[10px]"><thead className="sticky top-0 bg-brand-offwhite"><tr><th className="text-left p-2">Name</th><th className="text-right p-2">tCO2e</th><th className="text-right p-2">Intensity</th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.key} className="border-t border-brand-border hover:bg-brand-offwhite cursor-pointer" onClick={()=>onDrill(row.key)}><td className="p-2">{row.name}</td><td className="p-2 text-right font-mono">{row.emissions.toFixed(2)}</td><td className="p-2 text-right font-mono">{row.intensity===null?'Needs output':row.intensity.toFixed(1)}</td></tr>)}</tbody></table></div>;
  if(widget.widget_type==='heatmap'||widget.widget_type==='map')return <div className="grid grid-cols-2 gap-2">{data.series.facility.map((row:any,index:number)=><button key={row.key} onClick={()=>onDrill(row.key)} className="p-3 text-left border border-brand-border" style={{backgroundColor:`${colors[index%colors.length]}20`}}><p className="text-xs font-bold truncate">{row.name}</p><p className="text-[10px] font-mono mt-1">{row.emissions.toFixed(1)} tCO2e</p><p className="text-[9px] text-gray-500">{widget.widget_type==='map'?'Facility location view':row.intensity===null?'No intensity':`${row.intensity.toFixed(1)} kg/t`}</p></button>)}</div>;
  if(widget.widget_type==='insight'&&widget.dimension==='insights')return <div className="space-y-2">{data.insights.map((item:any,index:number)=><div key={index} className={`border-l-4 p-3 text-xs ${item.severity==='attention'?'border-brand-amber bg-amber-50':'border-brand-forest bg-brand-offwhite'}`}>{item.text}<p className="text-[9px] text-gray-400 mt-1">Derived from current filtered calculations; no causality inferred.</p></div>)}</div>;
  if(widget.widget_type==='insight'&&widget.dimension==='scenario')return <div className="space-y-2">{data.scenarioComparison.length?data.scenarioComparison.map((item:any)=><div key={item.id} className="border border-brand-border p-3"><div className="flex justify-between gap-2"><p className="text-xs font-bold">{item.title}</p><span className="text-[10px] font-mono text-brand-forest">-{item.reductionPercent.toFixed(1)}%</span></div><div className="grid grid-cols-2 gap-2 mt-2 text-[10px]"><span>Baseline {item.baseline.toFixed(1)} t</span><span>Scenario {item.scenario.toFixed(1)} t</span></div></div>):<p className="text-xs text-gray-500">No saved scenarios are available for comparison.</p>}</div>;
  if(widget.widget_type==='insight')return <div className="space-y-3 text-xs"><p className="leading-relaxed">Projection uses ordinary least squares over {data.series.monthly.length} recorded monthly observations. It is a trend extension, not a forecast guarantee.</p>{data.forecast.map((row:any)=><div key={row.period} className="flex justify-between border-t border-brand-border pt-2"><span>{row.period}</span><strong>{row.value.toFixed(1)} tCO2e</strong></div>)}<p className="text-[9px] text-gray-400">Internal facility benchmark median: {data.benchmark.median===null?'Unavailable':`${data.benchmark.median.toFixed(1)} kgCO2e/t`}</p></div>;
  return <p className="text-xs text-gray-500">No compatible data for this widget.</p>;
}

function DrillDrawer({drill,rows,onClose}:{drill:{dimension:string;key:string;title:string};rows:any[];onClose:()=>void}) {
  const filtered=rows.filter(row=>{if(!drill.key)return true;if(drill.dimension==='facility')return row.facilityId===drill.key;if(drill.dimension==='source')return row.source===drill.key;if(drill.dimension==='scope')return row.scope===drill.key;return true;});
  return <div className="fixed inset-0 z-[280] bg-black/20 flex justify-end" onClick={onClose}><aside className="w-[760px] max-w-[95vw] h-full bg-white border-l border-brand-border shadow-xl p-5 overflow-auto" onClick={event=>event.stopPropagation()}><div className="flex justify-between"><div><p className="text-[10px] font-mono uppercase text-brand-forest">Drill-through</p><h2 className="text-lg font-black mt-1">{drill.title}</h2><p className="text-xs text-gray-500">{filtered.length} calculation records with factor and evidence lineage</p></div><button title="Close drill-through" onClick={onClose} className="studio-mini"><X/></button></div><div className="overflow-auto mt-5"><table className="w-full text-[10px]"><thead className="bg-brand-offwhite"><tr>{['Date','Facility','Scope','Source','Quantity','tCO2e','Status','Evidence'].map(item=><th key={item} className="text-left p-2">{item}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.calculationId} className="border-t border-brand-border"><td className="p-2 whitespace-nowrap">{row.date}</td><td className="p-2">{row.facility}</td><td className="p-2">{row.scope}</td><td className="p-2">{row.source}</td><td className="p-2 font-mono">{row.quantity} {row.unit}</td><td className="p-2 font-mono">{row.emissionsTco2e.toFixed(3)}</td><td className="p-2">{row.status}</td><td className="p-2">{row.evidenceCount}</td></tr>)}</tbody></table></div></aside></div>;
}
