import { useEffect, useMemo, useState } from 'react';
import { Bell, CheckCircle2, ClipboardCheck, Clock3, FileCheck2, MessageSquare, RefreshCw, Send, Siren, Users } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext.tsx';
import { safeFetchJson } from '../services/apiClient.ts';

type Workspace = { members:any[];tasks:any[];comments:any[];reviews:any[];evidenceRequests:any[];notifications:any[];activity:any[];documents:any[];documentApprovals:any[];emailOutbox:any[] };
const empty:Workspace={members:[],tasks:[],comments:[],reviews:[],evidenceRequests:[],notifications:[],activity:[],documents:[],documentApprovals:[],emailOutbox:[]};
const tabs=['work','tasks','reviews','evidence','comments','activity','notifications'] as const;
type Tab=(typeof tabs)[number];
const label=(value:string)=>value.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());
const date=(value?:string)=>value?new Date(value).toLocaleString():'No due date';

export default function CollaborationCenter(){
 const {can}=useAuth();const [data,setData]=useState<Workspace>(empty),[tab,setTab]=useState<Tab>('work'),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const [task,setTask]=useState({title:'',description:'',assigneeId:'',priority:'medium',dueAt:''});const [comment,setComment]=useState({message:'',mention:''});
 const [review,setReview]=useState({title:'',subjectType:'report',subjectId:'',reviewerId:'',dueAt:''});const [evidence,setEvidence]=useState({title:'',description:'',requestedFrom:'',dueAt:''});const [approval,setApproval]=useState({documentId:'',approverId:''});
 const load=async()=>{setLoading(true);const next=await safeFetchJson('/api/collaboration/workspace',undefined,null);if(next)setData({...empty,...next});else setMessage('Collaboration data is unavailable. Apply migration 028 and confirm your plan entitlement.');setLoading(false)};
 useEffect(()=>{void load()},[]);
 const mutate=async(url:string,method:string,body?:any)=>{setMessage('');const result=await safeFetchJson(url,{method,body:body?JSON.stringify(body):undefined},null);if(!result){setMessage('The workflow action could not be completed. Check permissions and required fields.');return}setMessage('Workflow updated.');await load()};
 const memberName=(id:string)=>data.members.find(m=>m.id===id)?.full_name||'Unassigned';const documentName=(id:string)=>data.documents.find(d=>d.id===id)?.name||id;
 const dueTasks=useMemo(()=>data.tasks.filter(t=>!['completed','cancelled'].includes(t.status)),[data.tasks]);const unread=data.notifications.filter(n=>!n.read_at).length;
 const card='bg-white border border-brand-border rounded-lg p-4';const input='w-full border border-brand-border rounded-md px-3 py-2 text-sm bg-white';const button='bg-brand-charcoal text-white rounded-md px-3 py-2 text-xs font-bold hover:bg-black disabled:opacity-40';
 if(loading)return <div className={`${card} min-h-80 flex items-center justify-center gap-2 text-sm text-gray-500`}><RefreshCw className="w-5 h-5 animate-spin"/>Loading collaboration workspace...</div>;
 return <div className="space-y-5 max-w-[1500px] mx-auto">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><span className="text-[10px] font-mono uppercase tracking-widest text-brand-forest">Governed teamwork</span><h1 className="text-2xl font-black mt-1">Collaboration Center</h1><p className="text-sm text-gray-500 mt-1">Assign work, collect evidence, review records, approve documents, and preserve an auditable activity trail.</p></div>{can('collaboration.manage')&&<button className={button} onClick={()=>mutate('/api/collaboration/escalations/run','POST')}><Siren className="w-4 h-4 inline mr-2"/>Run overdue escalations</button>}</div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[[dueTasks.length,'Open tasks',ClipboardCheck],[data.reviews.filter(r=>['requested','in-review'].includes(r.status)).length,'Pending reviews',Clock3],[data.evidenceRequests.filter(r=>r.status==='open').length,'Evidence requests',FileCheck2],[unread,'Unread notices',Bell]].map(([value,title,Icon]:any)=><div className={card} key={title}><Icon className="w-4 h-4 text-brand-forest"/><strong className="block text-2xl mt-3">{value}</strong><span className="text-xs text-gray-500">{title}</span></div>)}</div>
  <div className="flex gap-1 overflow-x-auto border-b border-brand-border">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`px-3 py-2 text-xs font-bold whitespace-nowrap border-b-2 ${tab===item?'border-brand-forest text-brand-forest':'border-transparent text-gray-500'}`}>{label(item)}</button>)}</div>
  {message&&<div className="border border-brand-border bg-brand-sage/30 px-4 py-3 text-sm rounded-md">{message}</div>}
  {tab==='work'&&<div className="grid lg:grid-cols-2 gap-4"><section className={card}><h2 className="font-bold flex gap-2"><Users className="w-5 h-5 text-brand-forest"/>My operational queue</h2><div className="mt-4 divide-y divide-brand-border">{dueTasks.slice(0,8).map(t=><Row key={t.id} title={t.title} meta={`${memberName(t.assignee_id)} · ${label(t.priority)} · ${date(t.due_at)}`} status={t.status}/>)||null}{!dueTasks.length&&<Empty/>}</div></section><section className={card}><h2 className="font-bold">Automation status</h2><div className="mt-4 grid grid-cols-2 gap-3"><Stat value={data.emailOutbox.filter(x=>x.status==='queued').length} label="Queued emails"/><Stat value={data.activity.length} label="Recent audit events"/></div><p className="text-xs text-gray-500 mt-4">In-app notifications are active. Email messages are recorded in the outbox; delivery requires a configured mail worker.</p></section></div>}
  {tab==='tasks'&&<div className="grid xl:grid-cols-[360px_1fr] gap-4">{can('collaboration.manage')&&<form className={`${card} space-y-3`} onSubmit={e=>{e.preventDefault();void mutate('/api/collaboration/tasks','POST',task)}}><h2 className="font-bold">Create task</h2><input className={input} placeholder="Task title" value={task.title} onChange={e=>setTask({...task,title:e.target.value})} required/><textarea className={input} placeholder="Description" value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/><Select className={input} value={task.assigneeId} onChange={v=>setTask({...task,assigneeId:v})} items={data.members} placeholder="Assign member"/><select className={input} value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select><input className={input} type="datetime-local" value={task.dueAt} onChange={e=>setTask({...task,dueAt:e.target.value})}/><button className={button}>Create task</button></form>}<section className={`${card} divide-y divide-brand-border`}>{data.tasks.map(t=><div className="py-3 flex flex-col md:flex-row md:items-center justify-between gap-3" key={t.id}><Row title={t.title} meta={`${memberName(t.assignee_id)} · ${date(t.due_at)}`} status={t.status}/>{!['completed','cancelled'].includes(t.status)&&<select className="border border-brand-border rounded px-2 py-1 text-xs" value={t.status} onChange={e=>mutate(`/api/collaboration/tasks/${t.id}`,'PATCH',{status:e.target.value})}>{['open','in-progress','blocked','completed','cancelled'].map(x=><option key={x}>{x}</option>)}</select>}</div>)}{!data.tasks.length&&<Empty/>}</section></div>}
  {tab==='reviews'&&<div className="space-y-4">{can('collaboration.manage')&&<form className={`${card} grid md:grid-cols-2 xl:grid-cols-6 gap-3`} onSubmit={e=>{e.preventDefault();void mutate('/api/collaboration/reviews','POST',review)}}><input className={input} placeholder="Review title" value={review.title} onChange={e=>setReview({...review,title:e.target.value})} required/><input className={input} placeholder="Subject ID" value={review.subjectId} onChange={e=>setReview({...review,subjectId:e.target.value})} required/><select className={input} value={review.subjectType} onChange={e=>setReview({...review,subjectType:e.target.value})}>{['report','document','activity','project'].map(x=><option key={x}>{x}</option>)}</select><Select className={input} value={review.reviewerId} onChange={v=>setReview({...review,reviewerId:v})} items={data.members} placeholder="Reviewer"/><input className={input} type="datetime-local" value={review.dueAt} onChange={e=>setReview({...review,dueAt:e.target.value})}/><button className={button}>Request review</button></form>}<section className={`${card} divide-y divide-brand-border`}>{data.reviews.map(r=><ActionRow key={r.id} title={r.title} meta={`${memberName(r.reviewer_id)} · ${r.subject_type}: ${r.subject_id}`} status={r.status} actions={['in-review','approved','changes-requested','rejected']} onAction={status=>mutate(`/api/collaboration/reviews/${r.id}`,'PATCH',{status})}/>)}{!data.reviews.length&&<Empty/>}</section></div>}
  {tab==='evidence'&&<div className="space-y-4">{can('collaboration.manage')&&<form className={`${card} grid md:grid-cols-2 xl:grid-cols-5 gap-3`} onSubmit={e=>{e.preventDefault();void mutate('/api/collaboration/evidence-requests','POST',evidence)}}><input className={input} placeholder="Evidence needed" value={evidence.title} onChange={e=>setEvidence({...evidence,title:e.target.value})} required/><input className={input} placeholder="Instructions" value={evidence.description} onChange={e=>setEvidence({...evidence,description:e.target.value})}/><Select className={input} value={evidence.requestedFrom} onChange={v=>setEvidence({...evidence,requestedFrom:v})} items={data.members} placeholder="Evidence owner"/><input className={input} type="datetime-local" value={evidence.dueAt} onChange={e=>setEvidence({...evidence,dueAt:e.target.value})}/><button className={button}>Request evidence</button></form>}<section className={`${card} divide-y divide-brand-border`}>{data.evidenceRequests.map(r=><ActionRow key={r.id} title={r.title} meta={`${memberName(r.requested_from)} · ${r.document_id?documentName(r.document_id):'No document linked'}`} status={r.status} actions={['submitted','accepted','changes-requested','cancelled']} onAction={status=>mutate(`/api/collaboration/evidence-requests/${r.id}`,'PATCH',{status,documentId:r.document_id||data.documents[0]?.id})}/>)}{!data.evidenceRequests.length&&<Empty/>}</section><form className={`${card} grid md:grid-cols-3 gap-3`} onSubmit={e=>{e.preventDefault();void mutate('/api/collaboration/document-approvals','POST',approval)}}><Select className={input} value={approval.documentId} onChange={v=>setApproval({...approval,documentId:v})} items={data.documents.map(d=>({...d,full_name:d.name}))} placeholder="Document"/><Select className={input} value={approval.approverId} onChange={v=>setApproval({...approval,approverId:v})} items={data.members} placeholder="Approver"/><button className={button}>Request document approval</button></form><section className={`${card} divide-y divide-brand-border`}>{data.documentApprovals.map(a=><ActionRow key={a.id} title={documentName(a.document_id)} meta={`Approver: ${memberName(a.reviewer_id)}`} status={a.status} actions={['approved','changes-requested','rejected']} onAction={status=>mutate(`/api/collaboration/document-approvals/${a.id}`,'PATCH',{status})}/>)}</section></div>}
  {tab==='comments'&&<div className="grid xl:grid-cols-[380px_1fr] gap-4"><form className={`${card} space-y-3`} onSubmit={e=>{e.preventDefault();void mutate('/api/collaboration/comments','POST',{message:comment.message,subjectType:'workspace',subjectId:'collaboration-center',mentions:comment.mention?[comment.mention]:[]});setComment({...comment,message:''})}}><h2 className="font-bold">Add workspace comment</h2><textarea className={input} placeholder="Comment" value={comment.message} onChange={e=>setComment({...comment,message:e.target.value})} required/><Select className={input} value={comment.mention} onChange={v=>setComment({...comment,mention:v})} items={data.members} placeholder="Mention a member (optional)"/><button className={button}><Send className="w-4 h-4 inline mr-2"/>Post comment</button></form><section className={`${card} divide-y divide-brand-border`}>{data.comments.map(c=><Row key={c.id} title={c.message} meta={`${memberName(c.created_by)} · ${date(c.created_at)}`} status={c.subject_type}/>)}{!data.comments.length&&<Empty/>}</section></div>}
  {tab==='activity'&&<section className={`${card} divide-y divide-brand-border`}>{data.activity.map(a=><Row key={a.id} title={a.summary} meta={`${memberName(a.actor_id)} · ${date(a.created_at)}`} status={a.event_type}/>)}{!data.activity.length&&<Empty/>}</section>}
  {tab==='notifications'&&<section className={`${card} divide-y divide-brand-border`}>{data.notifications.map(n=><div key={n.id} className="py-3 flex justify-between gap-4"><Row title={n.title} meta={`${n.body} · ${date(n.created_at)}`} status={n.read_at?'read':'unread'}/>{!n.read_at&&<button title="Mark read" className="text-brand-forest" onClick={()=>mutate(`/api/collaboration/notifications/${n.id}/read`,'PATCH')}><CheckCircle2 className="w-5 h-5"/></button>}</div>)}{!data.notifications.length&&<Empty/>}</section>}
 </div>
}
function Select({items,value,onChange,placeholder,className}:{items:any[];value:string;onChange:(v:string)=>void;placeholder:string;className:string}){return <select className={className} value={value} onChange={e=>onChange(e.target.value)} required><option value="">{placeholder}</option>{items.map(x=><option value={x.id} key={x.id}>{x.full_name||x.name||x.id}</option>)}</select>}
function Row({title,meta,status}:{title:string;meta:string;status:string}){return <div className="py-2 min-w-0"><div className="flex items-center gap-2"><strong className="text-sm break-words">{title}</strong><span className="text-[9px] font-mono uppercase bg-brand-offwhite border border-brand-border px-2 py-0.5 rounded">{label(status)}</span></div><p className="text-xs text-gray-500 mt-1 break-all">{meta}</p></div>}
function ActionRow({title,meta,status,actions,onAction}:{title:string;meta:string;status:string;actions:string[];onAction:(s:string)=>void}){return <div className="py-3 flex flex-col md:flex-row md:items-center justify-between gap-3"><Row title={title} meta={meta} status={status}/>{!['approved','rejected','cancelled','completed'].includes(status)&&<select className="border border-brand-border rounded px-2 py-1 text-xs" value="" onChange={e=>e.target.value&&onAction(e.target.value)}><option value="">Choose action</option>{actions.map(x=><option value={x} key={x}>{label(x)}</option>)}</select>}</div>}
function Empty(){return <p className="text-sm text-gray-400 py-8 text-center">No records yet.</p>}
function Stat({value,label:caption}:{value:number;label:string}){return <div className="bg-brand-offwhite border border-brand-border rounded-md p-3"><strong className="text-xl">{value}</strong><span className="block text-xs text-gray-500">{caption}</span></div>}
