import {useEffect,useState} from 'react';
import {ArrowUpRight,BarChart3,CheckCircle2,FileCheck2,Globe2,Leaf,RefreshCw,ShieldCheck,Target,Users} from 'lucide-react';
import AsymmetricInfinityLogo from './AsymmetricInfinityLogo.tsx';

const fmt=(value:any,digits=1)=>Number(value??0).toLocaleString(undefined,{maximumFractionDigits:digits});
export default function PublicESGPortal({slug}:{slug:string}){const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{fetch(`/api/public/portals/${encodeURIComponent(slug)}`).then(async response=>{if(!response.ok)throw new Error('This ESG portal is not currently published.');setData((await response.json()).data)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[slug]);if(loading)return <main className="min-h-screen flex items-center justify-center gap-2"><RefreshCw className="w-5 h-5 animate-spin"/>Loading public disclosure...</main>;if(error||!data)return <main className="min-h-screen bg-brand-offwhite flex items-center justify-center p-6"><div className="bg-white border border-brand-border rounded-lg p-8 max-w-lg text-center"><Globe2 className="w-8 h-8 text-brand-forest mx-auto"/><h1 className="text-xl font-black mt-4">Portal unavailable</h1><p className="text-sm text-gray-500 mt-2">{error}</p><a className="inline-block mt-5 text-sm font-bold text-brand-forest" href="/">Return to Balancing Carbon</a></div></main>;
 const sections:string[]=data.portal.sections??[],theme=data.portal.theme??{},has=(key:string)=>sections.includes(key);return <div className="min-h-screen bg-[#f7f8f5] text-brand-charcoal" style={{'--portal-primary':theme.primaryColor??'#173f2a','--portal-accent':theme.accentColor??'#d39b35'} as any}>
  <header className="bg-white border-b border-brand-border px-5 py-4"><div className="max-w-7xl mx-auto flex items-center justify-between gap-4"><AsymmetricInfinityLogo size="sm"/><span className="text-[10px] font-mono uppercase tracking-widest text-gray-500">Public ESG Disclosure</span></div></header>
  <section className="bg-[var(--portal-primary)] text-white px-5 pt-14 pb-20"><div className="max-w-7xl mx-auto"><p className="text-xs font-mono uppercase tracking-widest text-white/65">{data.organization.industry} · {data.organization.location}</p><h1 className="text-4xl md:text-6xl font-black mt-4 max-w-5xl">{data.organization.name}</h1><p className="text-lg md:text-xl text-white/75 max-w-3xl mt-5 leading-relaxed">{data.portal.summary}</p><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-xs font-mono text-white/70"><span>Reporting period: {data.organization.reporting_year}</span><span>Snapshot: {new Date(data.generatedAt).toLocaleDateString()}</span><span>Versioned public disclosure</span></div></div></section>
  {has('overview')&&<section className="px-5 -mt-9"><div className="max-w-7xl mx-auto bg-white border border-brand-border rounded-lg grid sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total footprint" value={`${fmt(data.carbon.totalTco2e)} tCO2e`} icon={Leaf}/><Metric label="Approved ESG indicators" value={data.esg.approvedIndicators} icon={ShieldCheck}/><Metric label="Active public targets" value={data.targets.length} icon={Target}/><Metric label="Supplier response" value={`${data.suppliers.responseRate}%`} icon={Users}/></div></section>}
  {has('carbon')&&<Band title="Carbon dashboard" eyebrow="Current published inventory" icon={BarChart3}><div className="grid lg:grid-cols-[1fr_1.2fr] gap-8"><div><strong className="text-5xl font-black">{fmt(data.carbon.totalTco2e)}</strong><span className="block text-sm text-gray-500 mt-1">tonnes CO2 equivalent</span><p className="text-sm text-gray-600 leading-relaxed mt-6">{data.carbon.methodologyNote}</p><p className="text-xs font-mono text-gray-400 mt-4">Verified calculation share: {data.carbon.verifiedCalculationShare}%</p></div><div className="space-y-5"><Bar label="Scope 1" value={data.carbon.scope1Tco2e} total={data.carbon.totalTco2e}/><Bar label="Scope 2" value={data.carbon.scope2Tco2e} total={data.carbon.totalTco2e}/></div></div></Band>}
  {has('esg')&&<Band title="ESG performance" eyebrow="Approved indicators only" icon={ShieldCheck} tone="white"><div className="grid md:grid-cols-3 gap-4"><Metric label="Average approved score" value={data.esg.averageScore===null?'Not reported':`${data.esg.averageScore}%`} icon={ShieldCheck}/><Metric label="Compliant indicators" value={data.esg.compliantIndicators} icon={CheckCircle2}/><Metric label="Compliance share" value={`${data.esg.complianceShare}%`} icon={BarChart3}/></div><p className="text-xs text-gray-500 mt-5">{data.esg.note}</p></Band>}
  {has('targets')&&<Band title="Targets and progress" eyebrow="Public climate targets" icon={Target}><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{data.targets.map((target:any)=><article className="bg-white border border-brand-border rounded-lg p-5" key={target.id}><p className="text-[10px] uppercase font-mono text-brand-forest">{target.framework} · {target.status}</p><h3 className="font-black mt-2">{target.name}</h3><p className="text-sm text-gray-500 mt-2">{target.baseline_year} baseline to {target.target_year} target</p><strong className="text-2xl block mt-5">{fmt(target.target_value)} {target.unit}</strong>{target.progressPercent!==null&&<div className="mt-4"><div className="h-2 bg-gray-100"><div className="h-full bg-[var(--portal-primary)]" style={{width:`${target.progressPercent}%`}}/></div><small className="text-gray-500">{target.progressPercent}% progress</small></div>}</article>)}{!data.targets.length&&<Empty text="No approved public targets in this snapshot."/>}</div></Band>}
  {(has('commitments')||has('policies')||has('certificates'))&&<Band title="Commitments and governance" eyebrow="Published statements" icon={FileCheck2} tone="white"><div className="grid lg:grid-cols-3 gap-6">{has('commitments')&&<List title="Climate commitments" items={data.commitments}/>} {has('policies')&&<List title="Policies" items={data.policies}/>} {has('certificates')&&<List title="Certificates" items={data.certificates}/>}</div></Band>}
  {has('reports')&&<Band title="Reports and resources" eyebrow="Selected public metadata" icon={FileCheck2}><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{data.assets.map((asset:any,index:number)=><article className="bg-white border border-brand-border rounded-lg p-5" key={`${asset.title}-${index}`}><p className="text-[10px] uppercase font-mono text-brand-forest">{asset.type}</p><h3 className="font-black mt-2">{asset.title}</h3><p className="text-sm text-gray-500 mt-3">{asset.summary}</p></article>)}{!data.assets.length&&<Empty text="No public resources selected for this snapshot."/>}</div></Band>}
  {has('suppliers')&&<Band title="Supplier engagement" eyebrow="Aggregate supply-chain readiness" icon={Users} tone="white"><div className="grid sm:grid-cols-3 gap-4"><Metric label="Suppliers assessed" value={data.suppliers.totalSuppliers} icon={Users}/><Metric label="Responses received" value={data.suppliers.respondedSuppliers} icon={CheckCircle2}/><Metric label="Verified suppliers" value={data.suppliers.verifiedSuppliers} icon={ShieldCheck}/></div><p className="text-xs text-gray-500 mt-5">{data.suppliers.note}</p></Band>}
  <footer className="bg-brand-charcoal text-white px-5 py-10"><div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between gap-5"><div><strong>{data.organization.name}</strong><p className="text-xs text-white/60 mt-2">{data.disclosures.contact}</p></div><div className="text-xs text-white/60 max-w-xl"><p>{data.disclosures.boundary}</p><p className="mt-2">{data.disclosures.limitation}</p></div><a href="/" className="text-xs font-bold flex items-center gap-1">Powered by Balancing Carbon <ArrowUpRight className="w-4 h-4"/></a></div></footer>
 </div>}
function Band({title,eyebrow,icon:Icon,children,tone='soft'}:{title:string;eyebrow:string;icon:any;children:any;tone?:string}){return <section className={`${tone==='white'?'bg-white':'bg-[#f7f8f5]'} px-5 py-16 border-b border-brand-border/60`}><div className="max-w-7xl mx-auto"><div className="flex gap-3 items-start mb-8"><Icon className="w-5 h-5 text-brand-forest mt-1"/><div><p className="text-[10px] uppercase font-mono tracking-widest text-gray-500">{eyebrow}</p><h2 className="text-2xl md:text-3xl font-black mt-1">{title}</h2></div></div>{children}</div></section>}
function Metric({label,value,icon:Icon}:{label:string;value:any;icon:any}){return <div className="p-5 border-b sm:border-b-0 sm:border-r last:border-r-0 border-brand-border"><Icon className="w-4 h-4 text-brand-forest"/><strong className="text-2xl block mt-4">{value}</strong><span className="text-xs text-gray-500">{label}</span></div>}
function Bar({label,value,total}:{label:string;value:number;total:number}){const share=total?Math.min(100,value/total*100):0;return <div><div className="flex justify-between text-sm"><strong>{label}</strong><span>{fmt(value)} tCO2e · {fmt(share,0)}%</span></div><div className="h-3 bg-gray-200 mt-2"><div className="h-full bg-[var(--portal-primary)]" style={{width:`${share}%`}}/></div></div>}
function List({title,items}:{title:string;items:any[]}){return <div><h3 className="font-black border-b border-brand-border pb-3">{title}</h3><div className="divide-y divide-brand-border">{items.map((item,index)=><article className="py-4" key={`${item.title}-${index}`}><strong className="text-sm">{item.title}</strong><p className="text-xs text-gray-500 mt-1">{item.summary}</p>{item.date&&<small className="font-mono text-gray-400">{item.date}</small>}</article>)}{!items.length&&<p className="text-sm text-gray-400 py-5">No published items.</p>}</div></div>}
function Empty({text}:{text:string}){return <div className="border border-dashed border-brand-border rounded-lg p-8 text-center text-sm text-gray-400">{text}</div>}
