import {useEffect,useMemo,useState} from 'react';
import {ExternalLink,Eye,Globe2,RefreshCw,Save,Send,ShieldCheck} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext.tsx';
import {safeFetchJson} from '../services/apiClient.ts';

const sections=['overview','carbon','esg','targets','reports','certificates','policies','commitments','suppliers','investors'];
const parseItems=(text:string)=>text.split('\n').map(line=>{const [title,summary,date]=line.split('|').map(v=>v?.trim()||'');return{title,summary,date}}).filter(x=>x.title);
const formatItems=(items:any[]=[])=>items.map(x=>[x.title,x.summary,x.date].filter(Boolean).join(' | ')).join('\n');

export default function PublicPortalAdmin(){
 const {can}=useAuth(),[loading,setLoading]=useState(true),[data,setData]=useState<any>({portal:null,assets:[],sources:{reports:[],documents:[]}}),[message,setMessage]=useState('');
 const [form,setForm]=useState<any>({title:'',slug:'',summary:'',enabledSections:['overview','carbon','esg','targets','reports','commitments'],contact:'',commitments:'',policies:'',certificates:'',primaryColor:'#173f2a',accentColor:'#d39b35'}),[selected,setSelected]=useState<string[]>([]);
 const load=async()=>{setLoading(true);const next=await safeFetchJson('/api/portal/admin',undefined,null);if(next){setData(next);const p=next.portal;if(p)setForm({title:p.title,slug:p.slug,summary:p.summary,enabledSections:p.enabled_sections??[],contact:p.content?.contact??'',commitments:formatItems(p.content?.commitments),policies:formatItems(p.content?.policies),certificates:formatItems(p.content?.certificates),primaryColor:p.theme?.primaryColor??'#173f2a',accentColor:p.theme?.accentColor??'#d39b35'});setSelected((next.assets??[]).map((x:any)=>x.asset_id))}else setMessage('Portal administration is unavailable. Apply migration 029 and confirm Enterprise entitlement.');setLoading(false)};
 useEffect(()=>{void load()},[]);
 const request=async(url:string,method:string,body?:any)=>{setMessage('');const result=await safeFetchJson(url,{method,body:body?JSON.stringify(body):undefined},null);if(!result){setMessage('Action failed. Check required fields, permission, entitlement, and slug uniqueness.');return null}setMessage('Portal updated successfully.');await load();return result};
 const save=async()=>request('/api/portal/admin','PUT',{id:data.portal?.id,title:form.title,slug:form.slug,summary:form.summary,enabledSections:form.enabledSections,content:{contact:form.contact,commitments:parseItems(form.commitments),policies:parseItems(form.policies),certificates:parseItems(form.certificates)},theme:{primaryColor:form.primaryColor,accentColor:form.accentColor}});
 const saveAssets=async()=>request('/api/portal/admin/assets','PUT',{assets:selected.map(assetId=>({assetId}))});
 const publish=async()=>{await save();await saveAssets();return request('/api/portal/admin/publish','POST',{changeSummary:'Published from portal administration.'})};
 const available=useMemo(()=>[...(data.sources?.reports??[]).map((x:any)=>({...x,label:x.title,kind:'report'})),...(data.sources?.documents??[]).map((x:any)=>({...x,label:x.name,kind:'document'}))],[data]);
 const input='w-full border border-brand-border rounded-md px-3 py-2 text-sm bg-white';const panel='bg-white border border-brand-border rounded-lg p-5';const primary='bg-brand-charcoal text-white rounded-md px-4 py-2 text-xs font-bold disabled:opacity-40 flex items-center justify-center gap-2';
 if(loading)return <div className={`${panel} min-h-80 flex items-center justify-center gap-2 text-sm text-gray-500`}><RefreshCw className="w-5 h-5 animate-spin"/>Loading portal administration...</div>;
 return <div className="max-w-[1450px] mx-auto space-y-5">
  <header className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><p className="text-[10px] uppercase font-mono tracking-widest text-brand-forest">Phase 13 publication control</p><h1 className="text-2xl font-black mt-1">Public ESG Portal</h1><p className="text-sm text-gray-500 mt-1">Choose exactly what external stakeholders can see, then publish an immutable point-in-time snapshot.</p></div><div className="flex flex-wrap gap-2">{data.portal?.status==='published'&&<a className={primary} href={`/portal/${data.portal.slug}`} target="_blank" rel="noreferrer"><ExternalLink className="w-4 h-4"/>Open public portal</a>}{can('public_portal.publish')&&<button className={primary} onClick={()=>void publish()}><Send className="w-4 h-4"/>Publish snapshot</button>}</div></header>
  {message&&<div className="border border-brand-border bg-brand-sage/30 px-4 py-3 rounded-md text-sm">{message}</div>}
  <div className="grid xl:grid-cols-[1fr_420px] gap-5"><div className="space-y-5"><section className={panel}><div className="flex items-center gap-2"><Globe2 className="w-5 h-5 text-brand-forest"/><h2 className="font-bold">Identity and public URL</h2></div><div className="grid md:grid-cols-2 gap-3 mt-4"><label className="text-xs font-bold">Portal title<input className={`${input} mt-1`} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="text-xs font-bold">Public slug<input className={`${input} mt-1`} value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})}/></label></div><label className="text-xs font-bold block mt-3">Public summary<textarea className={`${input} mt-1 min-h-24`} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label className="text-xs font-bold block mt-3">Public contact<input className={`${input} mt-1`} value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label></section>
   <section className={panel}><h2 className="font-bold">Published sections</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-4">{sections.map(section=><label className="border border-brand-border rounded-md px-3 py-2 flex items-center gap-2 text-sm" key={section}><input type="checkbox" checked={form.enabledSections.includes(section)} onChange={()=>setForm({...form,enabledSections:form.enabledSections.includes(section)?form.enabledSections.filter((x:string)=>x!==section):[...form.enabledSections,section]})}/><span className="capitalize">{section}</span></label>)}</div></section>
   <section className={panel}><h2 className="font-bold">Commitments, policies and certificates</h2><p className="text-xs text-gray-500 mt-1">One item per line: Title | Summary | Date</p>{[['commitments','Climate commitments'],['policies','Policies'],['certificates','Certificates']].map(([key,title])=><label className="text-xs font-bold block mt-4" key={key}>{title}<textarea className={`${input} mt-1 min-h-24`} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</section>
   <section className={panel}><h2 className="font-bold">Selected public resources</h2><p className="text-xs text-gray-500 mt-1">Only metadata is published. Private document files and storage URLs remain private.</p><div className="mt-4 divide-y divide-brand-border max-h-80 overflow-y-auto">{available.map((asset:any)=><label className="py-3 flex items-start gap-3" key={asset.id}><input className="mt-1" type="checkbox" checked={selected.includes(asset.id)} onChange={()=>setSelected(selected.includes(asset.id)?selected.filter(x=>x!==asset.id):[...selected,asset.id])}/><span><strong className="text-sm block">{asset.label}</strong><small className="text-gray-500 uppercase font-mono">{asset.kind} · {asset.period??asset.category}</small></span></label>)}{!available.length&&<p className="text-sm text-gray-400 py-8 text-center">No reports or documents are available.</p>}</div></section>
  </div><aside className="space-y-5"><section className={`${panel} xl:sticky xl:top-0`}><div className="flex justify-between"><div><p className="text-[10px] uppercase font-mono text-gray-400">Publication state</p><h2 className="text-xl font-black mt-1 capitalize">{data.portal?.status??'Not configured'}</h2></div><ShieldCheck className="w-6 h-6 text-brand-forest"/></div><dl className="mt-5 text-sm divide-y divide-brand-border"><Info label="Snapshot version" value={data.portal?.snapshot_version??0}/><Info label="Published at" value={data.portal?.published_at?new Date(data.portal.published_at).toLocaleString():'Never'}/><Info label="Selected assets" value={selected.length}/><Info label="Enabled sections" value={form.enabledSections.length}/></dl><div className="grid grid-cols-2 gap-3 mt-5"><label className="text-xs font-bold">Primary<input type="color" className="w-full h-10 mt-1" value={form.primaryColor} onChange={e=>setForm({...form,primaryColor:e.target.value})}/></label><label className="text-xs font-bold">Accent<input type="color" className="w-full h-10 mt-1" value={form.accentColor} onChange={e=>setForm({...form,accentColor:e.target.value})}/></label></div>{can('public_portal.manage')&&<button className={`${primary} w-full mt-5`} onClick={()=>void save()}><Save className="w-4 h-4"/>Save draft</button>}{data.portal?.status==='published'&&can('public_portal.publish')&&<button className="w-full border border-brand-border rounded-md px-4 py-2 text-xs font-bold mt-2" onClick={()=>void request('/api/portal/admin/unpublish','POST')}>Withdraw public portal</button>}<div className="bg-brand-offwhite border border-brand-border rounded-md p-3 mt-5"><p className="text-xs flex gap-2"><Eye className="w-4 h-4 text-brand-forest shrink-0"/>Publishing never exposes live ledgers. It creates a versioned snapshot that remains unchanged until republished.</p></div></section></aside></div>
 </div>;
}
function Info({label,value}:{label:string;value:any}){return <div className="py-3 flex justify-between gap-4"><dt className="text-gray-500">{label}</dt><dd className="font-bold text-right">{value}</dd></div>}
