import { useEffect, useMemo, useState } from 'react';
import { AlignLeft, BarChart3, BookOpen, Bot, Check, ChevronDown, ChevronUp, Download, FileImage, FilePlus2, FileSpreadsheet, FileText, GripVertical, Heading, Image, LayoutDashboard, Link2, LoaderCircle, Paintbrush, Plus, Presentation, Save, Send, ShieldCheck, Sparkles, Table2, Trash2, Undo2 } from 'lucide-react';

import { getAuthenticatedHeaders, safeFetchJson } from '../services/apiClient.ts';

type Template = { id: string; name: string; report_type: string; description: string; compliance_frameworks?: { key: string; name: string } | null };
type Report = { id: string; title: string; type: string; period: string; workflowStatus: string; studioStatus?: string; brandKitId?: string | null; framework?: { key: string; name: string } | null };
type Evidence = { id: string; name: string; category: string };
type BrandKit = { id: string; name: string; primary_color: string; secondary_color: string; accent_color: string; footer_text: string; page_size: string };
type BlockType = 'heading' | 'narrative' | 'kpi-grid' | 'chart' | 'table' | 'image' | 'callout' | 'spacer' | 'page-break';
type StudioBlock = { id: string; block_type: BlockType; position: number; column_index?: number; title?: string; content: any; style?: any; data_binding?: any; source_label?: string; report_block_evidence?: Array<{ id: string; evidence_label: string; document_id: string }> };
type StudioPage = { id: string; page_number: number; title: string; layout: string; background_color: string; configuration?: any; report_studio_blocks: StudioBlock[] };
type DetailedReport = Report & { summary?: string; brandKit?: BrandKit | null; studioPages: StudioPage[]; currentVersion?: { version_number?: number; calculation_snapshot?: any; validation_snapshot?: any } | null; approvals?: Array<{ id: string; status: string }> };

const blockCatalog: Array<{ type: BlockType; label: string; icon: typeof Heading }> = [
  { type: 'heading', label: 'Heading', icon: Heading }, { type: 'narrative', label: 'Narrative', icon: AlignLeft }, { type: 'kpi-grid', label: 'KPI grid', icon: LayoutDashboard }, { type: 'chart', label: 'Chart', icon: BarChart3 }, { type: 'table', label: 'Table', icon: Table2 }, { type: 'image', label: 'Image', icon: Image }, { type: 'callout', label: 'Callout', icon: BookOpen }, { type: 'spacer', label: 'Spacer', icon: GripVertical },
];
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const statusLabel = (value?: string) => (value ?? 'draft').replaceAll('-', ' ');
const normalizePages = (pages: any[]): StudioPage[] => (pages ?? []).map((page, pageIndex) => ({ ...page, page_number: pageIndex + 1, title: page.title ?? `Page ${pageIndex + 1}`, layout: page.layout ?? 'single', background_color: page.background_color ?? '#ffffff', report_studio_blocks: [...(page.report_studio_blocks ?? page.blocks ?? [])].sort((a, b) => Number(a.position) - Number(b.position)).map((block, blockIndex) => ({ ...block, position: blockIndex, content: block.content ?? {}, style: block.style ?? {} })) }));
const defaultContent = (type: BlockType) => type === 'kpi-grid' ? { kpis: [{ label: 'Metric', value: '0', unit: 'tCO2e' }] } : type === 'table' ? { rows: [['Metric', 'Value'], ['Example', '0']] } : type === 'chart' ? { rows: [['Scope 1', 35], ['Scope 2', 65]], chartType: 'bar' } : type === 'image' ? { url: '', caption: '' } : { text: type === 'heading' ? 'Section heading' : '' };

export default function ReportingWorkspace() {
  const [templates, setTemplates] = useState<Template[]>([]); const [reports, setReports] = useState<Report[]>([]); const [documents, setDocuments] = useState<Evidence[]>([]); const [brandKits, setBrandKits] = useState<BrandKit[]>([]);
  const [selected, setSelected] = useState<DetailedReport | null>(null); const [pages, setPages] = useState<StudioPage[]>([]); const [activePageId, setActivePageId] = useState(''); const [activeBlockId, setActiveBlockId] = useState('');
  const [templateId, setTemplateId] = useState(''); const [period, setPeriod] = useState('FY 2025-26'); const [title, setTitle] = useState(''); const [brandKitId, setBrandKitId] = useState('');
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [aiTopic, setAiTopic] = useState('Executive sustainability summary'); const [aiDraft, setAiDraft] = useState(''); const [evidenceId, setEvidenceId] = useState('');
  const [draggedBlock, setDraggedBlock] = useState<{ pageId: string; blockId: string } | null>(null); const [brandForm, setBrandForm] = useState({ name: '', primaryColor: '#173f2a', secondaryColor: '#dce9df', accentColor: '#d39b35', footerText: 'Balancing Carbon', pageSize: 'A4' });
  const activePage = pages.find((page) => page.id === activePageId) ?? pages[0]; const activeBlock = activePage?.report_studio_blocks.find((block) => block.id === activeBlockId) ?? null;
  const editable = Boolean(selected && ['draft', 'changes-requested'].includes(selected.workflowStatus));
  const allBlocks = useMemo(() => pages.flatMap((page) => page.report_studio_blocks.map((block) => ({ ...block, pageTitle: page.title }))), [pages]);

  const load = async () => { setLoading(true); const [templateData, reportData, documentData, brandData] = await Promise.all([safeFetchJson('/api/reporting/templates', undefined, { templates: [] }), safeFetchJson('/api/reporting/reports', undefined, { reports: [] }), safeFetchJson('/api/documents', undefined, { documents: [] }), safeFetchJson('/api/reporting/brand-kits', undefined, { brandKits: [] })]); setTemplates(templateData?.templates ?? []); setReports(reportData?.reports ?? []); setDocuments(documentData?.documents ?? []); setBrandKits(brandData?.brandKits ?? []); setTemplateId((current) => current || templateData?.templates?.[0]?.id || ''); setEvidenceId(documentData?.documents?.[0]?.id || ''); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const acceptReport = (report: DetailedReport) => { const nextPages = normalizePages(report.studioPages ?? []); setSelected(report); setPages(nextPages); setBrandKitId(report.brandKit?.id ?? report.brandKitId ?? ''); setActivePageId(nextPages[0]?.id ?? ''); setActiveBlockId(nextPages[0]?.report_studio_blocks?.[0]?.id ?? ''); setAiDraft(''); setReports((items) => items.some((item) => item.id === report.id) ? items.map((item) => item.id === report.id ? report : item) : [report, ...items]); };
  const openReport = async (reportId: string) => { setBusy(true); const data = await safeFetchJson(`/api/reporting/reports/${reportId}`, undefined, null); if (data?.report) acceptReport(data.report); else setMessage('Unable to load this report. Run migration 024 if Phase 9 tables are not installed.'); setBusy(false); };
  const generate = async () => { if (!templateId) return; setBusy(true); const data = await safeFetchJson('/api/reporting/reports/generate', { method: 'POST', body: JSON.stringify({ templateId, period, title }) }, null); if (data?.report) { acceptReport(data.report); setTitle(''); setMessage('Report created with calculation-backed pages.'); } else setMessage('Report generation failed. Confirm calculation records and plan access.'); setBusy(false); };
  const mutatePage = (pageId: string, updater: (page: StudioPage) => StudioPage) => setPages((items) => items.map((page) => page.id === pageId ? updater(page) : page));
  const updateBlock = (patch: Partial<StudioBlock>) => activePage && activeBlock && mutatePage(activePage.id, (page) => ({ ...page, report_studio_blocks: page.report_studio_blocks.map((block) => block.id === activeBlock.id ? { ...block, ...patch } : block) }));
  const addPage = () => { const page: StudioPage = { id: id('studio-page'), page_number: pages.length + 1, title: `New page ${pages.length + 1}`, layout: 'single', background_color: '#ffffff', report_studio_blocks: [] }; setPages((items) => [...items, page]); setActivePageId(page.id); setActiveBlockId(''); };
  const addBlock = (type: BlockType) => { if (!activePage) return; const block: StudioBlock = { id: id('studio-block'), block_type: type, position: activePage.report_studio_blocks.length, title: type === 'heading' ? '' : blockCatalog.find((item) => item.type === type)?.label, content: defaultContent(type), style: {} }; mutatePage(activePage.id, (page) => ({ ...page, report_studio_blocks: [...page.report_studio_blocks, block] })); setActiveBlockId(block.id); };
  const removeBlock = () => { if (!activePage || !activeBlock) return; mutatePage(activePage.id, (page) => ({ ...page, report_studio_blocks: page.report_studio_blocks.filter((block) => block.id !== activeBlock.id) })); setActiveBlockId(''); };
  const removePage = () => { if (!activePage || pages.length === 1) return; const next = normalizePages(pages.filter((page) => page.id !== activePage.id)); setPages(next); setActivePageId(next[0]?.id ?? ''); setActiveBlockId(''); };
  const moveBlock = (delta: number) => { if (!activePage || !activeBlock) return; const blocks = [...activePage.report_studio_blocks], index = blocks.findIndex((block) => block.id === activeBlock.id), target = index + delta; if (target < 0 || target >= blocks.length) return; [blocks[index], blocks[target]] = [blocks[target], blocks[index]]; mutatePage(activePage.id, (page) => ({ ...page, report_studio_blocks: blocks.map((block, position) => ({ ...block, position })) })); };
  const dropBlock = (targetPageId: string, targetIndex: number) => { if (!draggedBlock) return; const moving = pages.find((page) => page.id === draggedBlock.pageId)?.report_studio_blocks.find((block) => block.id === draggedBlock.blockId); if (!moving) return; setPages((items) => items.map((page) => { let blocks = page.report_studio_blocks.filter((block) => block.id !== moving.id); if (page.id === targetPageId) { const insertion = Math.min(targetIndex, blocks.length); blocks = [...blocks.slice(0, insertion), moving, ...blocks.slice(insertion)]; } return { ...page, report_studio_blocks: blocks.map((block, position) => ({ ...block, position })) }; })); setActivePageId(targetPageId); setActiveBlockId(moving.id); setDraggedBlock(null); };
  const saveStudio = async () => { if (!selected || !editable) return false; setBusy(true); const data = await safeFetchJson(`/api/reporting/reports/${selected.id}/studio`, { method: 'PUT', body: JSON.stringify({ pages, brandKitId: brandKitId || null }) }, null); if (data?.report) { acceptReport(data.report); setMessage('Studio composition saved.'); setBusy(false); return true; } setMessage('Save failed. Check studio permissions and migration 024.'); setBusy(false); return false; };
  const createVersion = async () => { if (!selected || !(await saveStudio())) return; setBusy(true); const data = await safeFetchJson(`/api/reporting/reports/${selected.id}/studio/version`, { method: 'POST', body: JSON.stringify({ changeSummary: 'ESG Studio composition checkpoint.' }) }, null); if (data?.report) { acceptReport(data.report); setMessage(`Version ${data.report.currentVersion?.version_number} created.`); } else setMessage('Version checkpoint failed.'); setBusy(false); };
  const workflow = async (action: 'submit-review' | 'publish', approval?: 'approved' | 'changes-requested') => { if (!selected) return; setBusy(true); const endpoint = approval ? 'approvals' : action, body = approval ? { status: approval, comment: `${statusLabel(approval)} from ESG Reporting Studio.` } : { comment: `${statusLabel(action)} from ESG Reporting Studio.` }; const data = await safeFetchJson(`/api/reporting/reports/${selected.id}/${endpoint}`, { method: 'POST', body: JSON.stringify(body) }, null); if (data?.report) { acceptReport(data.report); setMessage(`Report ${approval ? statusLabel(approval) : statusLabel(action)}.`); } else setMessage('Workflow action was not allowed for your role or report status.'); setBusy(false); };
  const draftNarrative = async () => { if (!selected || !activeBlock) return; setBusy(true); const data = await safeFetchJson(`/api/reporting/reports/${selected.id}/studio/narrative`, { method: 'POST', body: JSON.stringify({ blockId: activeBlock.id, topic: aiTopic }) }, null); setAiDraft(data?.narrative?.generated_text ?? ''); setMessage(data?.narrative ? 'AI draft ready for human review.' : 'Narrative drafting failed. Confirm the local Ollama service is available.'); setBusy(false); };
  const linkEvidence = async () => { if (!selected || !activeBlock || !evidenceId) return; setBusy(true); const data = await safeFetchJson(`/api/reporting/reports/${selected.id}/studio/evidence`, { method: 'POST', body: JSON.stringify({ blockId: activeBlock.id, documentId: evidenceId }) }, null); if (data?.evidence) { setMessage('Evidence linked to this report block.'); await openReport(selected.id); } else setMessage('Evidence link could not be created.'); setBusy(false); };
  const createBrand = async () => { setBusy(true); const data = await safeFetchJson('/api/reporting/brand-kits', { method: 'POST', body: JSON.stringify(brandForm) }, null); if (data?.brandKit) { setBrandKits((items) => [data.brandKit, ...items]); setBrandKitId(data.brandKit.id); setBrandForm((form) => ({ ...form, name: '' })); setMessage('Brand kit created and selected.'); } else setMessage('Brand kit could not be created.'); setBusy(false); };
  const download = async (format: 'pdf' | 'docx' | 'pptx' | 'xlsx') => { if (!selected) return; setBusy(true); try { const response = await fetch(`/api/reporting/reports/${selected.id}/exports`, { method: 'POST', headers: { ...getAuthenticatedHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ format }) }); const data = await response.json(); if (!response.ok || !data?.export?.contentBase64) throw new Error(data?.error || 'Export failed.'); const raw = atob(data.export.contentBase64), bytes = Uint8Array.from(raw, (character) => character.charCodeAt(0)), url = URL.createObjectURL(new Blob([bytes], { type: data.export.mimeType })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = data.export.filename; anchor.click(); URL.revokeObjectURL(url); setMessage(`${format.toUpperCase()} export created.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Export failed.'); } setBusy(false); };

  if (loading) return <div className="min-h-72 flex items-center justify-center text-sm text-gray-500"><LoaderCircle className="w-5 h-5 animate-spin mr-2" />Loading ESG Reporting Studio...</div>;
  return <div className="space-y-4 min-w-0">
    <header className="bg-brand-charcoal text-white rounded-lg p-5 flex flex-col xl:flex-row xl:items-center xl:justify-between gap-4"><div><p className="text-[10px] font-mono uppercase text-brand-sage">Phase 9 | ESG Reporting Studio</p><h1 className="text-xl font-black mt-1">Build audit-ready sustainability reports</h1><p className="text-xs text-gray-300 mt-1">Compose, evidence, version, approve, publish, and export from one governed workspace.</p></div><div className="flex flex-wrap gap-2">{selected && <><button title="Save studio" onClick={saveStudio} disabled={busy || !editable} className="studio-action"><Save className="w-4 h-4" />Save</button><button title="Create version" onClick={createVersion} disabled={busy || !editable} className="studio-action"><FilePlus2 className="w-4 h-4" />Version</button>{(['pdf','docx','pptx','xlsx'] as const).map((format) => <button title={`Export ${format.toUpperCase()}`} key={format} onClick={() => void download(format)} disabled={busy} className="studio-icon-action">{format === 'pdf' ? <FileText /> : format === 'docx' ? <Download /> : format === 'pptx' ? <Presentation /> : <FileSpreadsheet />}</button>)}</>}</div></header>
    {message && <div className="border border-brand-border bg-white rounded px-4 py-2 text-xs text-brand-forest flex items-center gap-2"><Check className="w-4 h-4" />{message}</div>}
    <div className="grid grid-cols-1 2xl:grid-cols-[280px_minmax(520px,1fr)_310px] gap-4 items-start">
      <aside className="bg-white border border-brand-border rounded-lg overflow-hidden 2xl:sticky 2xl:top-4">
        <div className="p-4 border-b border-brand-border"><h2 className="text-xs font-black uppercase font-mono">Report library</h2><div className="mt-3 space-y-2"><select value={templateId} onChange={(event) => setTemplateId(event.target.value)} className="studio-input">{templates.map((template) => <option value={template.id} key={template.id}>{template.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input value={period} onChange={(event) => setPeriod(event.target.value)} className="studio-input" aria-label="Reporting period" /><input value={title} onChange={(event) => setTitle(event.target.value)} className="studio-input" placeholder="Title" aria-label="Report title" /></div><button onClick={generate} disabled={busy || !templateId} className="studio-primary w-full"><Plus className="w-4 h-4" />New report</button></div></div>
        <div className="max-h-72 overflow-auto divide-y divide-brand-border">{reports.map((report) => <button key={report.id} onClick={() => void openReport(report.id)} className={`w-full text-left p-3 hover:bg-brand-offwhite ${selected?.id === report.id ? 'bg-brand-sage/30' : ''}`}><p className="text-xs font-bold truncate">{report.title}</p><div className="flex justify-between mt-1 text-[10px] font-mono text-gray-500"><span>{report.period}</span><span className="capitalize">{statusLabel(report.workflowStatus)}</span></div></button>)}</div>
        {selected && <><div className="p-4 border-t border-brand-border"><div className="flex items-center justify-between"><h3 className="text-xs font-black uppercase font-mono">Pages</h3><button title="Add page" onClick={addPage} disabled={!editable} className="studio-mini"><Plus /></button></div><div className="mt-2 space-y-1">{pages.map((page) => <button key={page.id} onClick={() => { setActivePageId(page.id); setActiveBlockId(page.report_studio_blocks[0]?.id ?? ''); }} className={`w-full text-left px-2 py-2 rounded text-xs flex gap-2 ${activePage?.id === page.id ? 'bg-brand-charcoal text-white' : 'hover:bg-brand-offwhite'}`}><span className="font-mono opacity-60">{page.page_number}</span><span className="truncate">{page.title}</span></button>)}</div></div><div className="p-4 border-t border-brand-border"><h3 className="text-xs font-black uppercase font-mono">Add block</h3><div className="grid grid-cols-2 gap-1.5 mt-2">{blockCatalog.map(({ type, label, icon: Icon }) => <button key={type} onClick={() => addBlock(type)} disabled={!editable} className="studio-palette"><Icon className="w-3.5 h-3.5" />{label}</button>)}</div></div></>}
      </aside>
      <main className="min-w-0">{!selected ? <div className="bg-white border border-brand-border rounded-lg min-h-[560px] flex flex-col items-center justify-center text-center p-8"><FileText className="w-10 h-10 text-brand-forest" /><h2 className="text-lg font-black mt-3">Select or generate a report</h2><p className="text-sm text-gray-500 mt-1 max-w-md">Templates cover BRSR, GRI, ISSB, CSRD, TCFD, GHG Protocol, SECR, management carbon, and integrated reporting.</p></div> : <>
        <div className="bg-white border border-brand-border rounded-lg p-4 mb-4 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-base font-black">{selected.title}</h2><span className="studio-status">{statusLabel(selected.workflowStatus)}</span></div><p className="text-[11px] text-gray-500 mt-1">{selected.framework?.name ?? selected.type} | {selected.period} | Version {selected.currentVersion?.version_number ?? 1}</p></div><div className="flex flex-wrap gap-1.5">{editable && <button onClick={() => void workflow('submit-review')} disabled={selected.workflowStatus !== 'draft'} className="studio-secondary"><Send className="w-3.5 h-3.5" />Review</button>}{selected.workflowStatus === 'under-review' && <><button onClick={() => void workflow('submit-review','approved')} className="studio-primary">Approve</button><button onClick={() => void workflow('submit-review','changes-requested')} className="studio-secondary">Changes</button></>}{selected.workflowStatus === 'approved' && <button onClick={() => void workflow('publish')} className="studio-primary"><ShieldCheck className="w-3.5 h-3.5" />Publish</button>}</div></div>
        {activePage && <article className="report-canvas" style={{ backgroundColor: activePage.background_color }}><div className="flex items-center justify-between border-b border-brand-border pb-3 mb-5"><div className="min-w-0"><input value={activePage.title} onChange={(event) => mutatePage(activePage.id, (page) => ({ ...page, title: event.target.value }))} disabled={!editable} className="text-lg font-black bg-transparent w-full outline-none" /><p className="text-[10px] font-mono text-gray-400">PAGE {activePage.page_number} | {activePage.layout}</p></div><button title="Remove page" onClick={removePage} disabled={!editable || pages.length === 1} className="studio-mini text-red-700"><Trash2 /></button></div><div className={activePage.layout === 'two-column' ? 'grid md:grid-cols-2 gap-4' : 'space-y-3'} onDragOver={(event) => event.preventDefault()} onDrop={() => dropBlock(activePage.id, activePage.report_studio_blocks.length)}>{activePage.report_studio_blocks.map((block, blockIndex) => <div key={block.id} draggable={editable} onDragStart={() => setDraggedBlock({ pageId: activePage.id, blockId: block.id })} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.stopPropagation(); dropBlock(activePage.id, blockIndex); }} onClick={() => setActiveBlockId(block.id)} className={`report-block ${activeBlock?.id === block.id ? 'report-block-active' : ''}`}><GripVertical className="w-3.5 h-3.5 absolute left-1 top-3 text-gray-300" /><BlockPreview block={block} />{block.source_label && <p className="text-[9px] text-gray-400 mt-2">Source: {block.source_label}</p>}</div>)}{!activePage.report_studio_blocks.length && <button onClick={() => addBlock('heading')} className="w-full border border-dashed border-brand-border py-16 text-sm text-gray-400">Add the first content block</button>}</div><footer className="mt-8 pt-3 border-t border-brand-border text-[9px] text-gray-400 flex justify-between"><span>{brandKits.find((kit) => kit.id === brandKitId)?.footer_text || 'Balancing Carbon'}</span><span>{activePage.page_number}</span></footer></article>}</>}
      </main>
      <aside className="bg-white border border-brand-border rounded-lg overflow-hidden 2xl:sticky 2xl:top-4"><div className="p-4 border-b border-brand-border"><h2 className="text-xs font-black uppercase font-mono">Inspector</h2></div>{selected && activePage ? <div className="divide-y divide-brand-border">
        <section className="p-4 space-y-2"><div className="flex items-center justify-between"><h3 className="studio-inspector-title">Page</h3><button title="Remove selected block" onClick={removeBlock} disabled={!editable || !activeBlock} className="studio-mini text-red-700"><Trash2 /></button></div><select value={activePage.layout} disabled={!editable} onChange={(event) => mutatePage(activePage.id, (page) => ({ ...page, layout: event.target.value }))} className="studio-input"><option value="single">Single column</option><option value="two-column">Two columns</option><option value="cover">Cover</option><option value="full-bleed">Full bleed</option></select><div className="flex gap-2"><input type="color" value={activePage.background_color} disabled={!editable} onChange={(event) => mutatePage(activePage.id, (page) => ({ ...page, background_color: event.target.value }))} className="h-9 w-12 border border-brand-border rounded" /><button title="Move block up" onClick={() => moveBlock(-1)} disabled={!activeBlock || !editable} className="studio-mini"><ChevronUp /></button><button title="Move block down" onClick={() => moveBlock(1)} disabled={!activeBlock || !editable} className="studio-mini"><ChevronDown /></button></div></section>
        {activeBlock && <><section className="p-4 space-y-2"><h3 className="studio-inspector-title">{statusLabel(activeBlock.block_type)} block</h3><input value={activeBlock.title ?? ''} disabled={!editable} onChange={(event) => updateBlock({ title: event.target.value })} className="studio-input" placeholder="Block title" /><BlockEditor block={activeBlock} disabled={!editable} onChange={(content) => updateBlock({ content })} /><input value={activeBlock.source_label ?? ''} disabled={!editable} onChange={(event) => updateBlock({ source_label: event.target.value })} className="studio-input" placeholder="Source label" /><select className="studio-input" disabled={!editable} value="" onChange={(event) => { const target = allBlocks.find((block) => block.id === event.target.value); if (target) updateBlock({ content: { ...activeBlock.content, text: `${activeBlock.content?.text ?? ''} [[block:${target.id}]]`.trim() } }); }}><option value="">Insert cross-reference...</option>{allBlocks.filter((block) => block.id !== activeBlock.id && ['chart','table','image'].includes(block.block_type)).map((block) => <option key={block.id} value={block.id}>{block.pageTitle}: {block.title || statusLabel(block.block_type)}</option>)}</select></section>
        <section className="p-4 space-y-2"><h3 className="studio-inspector-title flex items-center gap-1.5"><Bot className="w-4 h-4" />AI narrative</h3><select value={aiTopic} onChange={(event) => setAiTopic(event.target.value)} className="studio-input"><option>Chairman message</option><option>CEO letter</option><option>Executive sustainability summary</option><option>Sustainability highlights</option><option>Risk overview</option><option>Progress against targets</option><option>Future sustainability roadmap</option></select><button onClick={draftNarrative} disabled={busy || !editable} className="studio-secondary w-full"><Sparkles className="w-4 h-4" />Draft from verified data</button>{aiDraft && <div className="bg-brand-offwhite border border-brand-border rounded p-2"><p className="text-xs leading-relaxed max-h-40 overflow-auto">{aiDraft}</p><div className="flex gap-2 mt-2"><button onClick={() => { updateBlock({ content: { ...activeBlock.content, text: aiDraft } }); setAiDraft(''); }} className="studio-primary flex-1">Apply draft</button><button title="Discard AI draft" onClick={() => setAiDraft('')} className="studio-mini"><Undo2 /></button></div></div>}</section>
        <section className="p-4 space-y-2"><h3 className="studio-inspector-title flex items-center gap-1.5"><Link2 className="w-4 h-4" />Evidence</h3><select value={evidenceId} onChange={(event) => setEvidenceId(event.target.value)} className="studio-input"><option value="">Choose document</option>{documents.map((document) => <option key={document.id} value={document.id}>{document.name}</option>)}</select><button onClick={linkEvidence} disabled={!evidenceId || busy} className="studio-secondary w-full">Link to block</button>{activeBlock.report_block_evidence?.map((evidence) => <p key={evidence.id} className="text-[10px] text-brand-forest flex gap-1"><FileImage className="w-3 h-3" />{evidence.evidence_label}</p>)}</section></>}
        <section className="p-4 space-y-2"><h3 className="studio-inspector-title flex items-center gap-1.5"><Paintbrush className="w-4 h-4" />Brand kit</h3><select value={brandKitId} onChange={(event) => setBrandKitId(event.target.value)} className="studio-input"><option value="">Default branding</option>{brandKits.map((kit) => <option key={kit.id} value={kit.id}>{kit.name}</option>)}</select><details><summary className="text-xs cursor-pointer text-brand-forest">Create brand kit</summary><div className="mt-2 space-y-2"><input value={brandForm.name} onChange={(event) => setBrandForm((form) => ({ ...form, name: event.target.value }))} className="studio-input" placeholder="Brand kit name" /><div className="flex gap-2">{(['primaryColor','secondaryColor','accentColor'] as const).map((key) => <input key={key} title={key} type="color" value={brandForm[key]} onChange={(event) => setBrandForm((form) => ({ ...form, [key]: event.target.value }))} className="h-9 flex-1 border border-brand-border rounded" />)}</div><input value={brandForm.footerText} onChange={(event) => setBrandForm((form) => ({ ...form, footerText: event.target.value }))} className="studio-input" placeholder="Footer text" /><button onClick={createBrand} disabled={!brandForm.name || busy} className="studio-primary w-full">Create</button></div></details></section>
      </div> : <p className="p-5 text-xs text-gray-500">Select a report and a content block to edit its properties.</p>}</aside>
    </div>
  </div>;
}

function BlockPreview({ block }: { block: StudioBlock }) {
  const text = String(block.content?.text ?? block.content?.narrative ?? '');
  if (block.block_type === 'heading') return <h3 className="text-xl font-black text-brand-charcoal">{text || block.title || 'Heading'}</h3>;
  if (['narrative','callout'].includes(block.block_type)) return <div className={block.block_type === 'callout' ? 'border-l-4 border-brand-forest bg-brand-offwhite p-3' : ''}>{block.title && <h4 className="text-sm font-black mb-1">{block.title}</h4>}<p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">{text || 'Add narrative content in the inspector.'}</p></div>;
  if (block.block_type === 'kpi-grid') return <div><h4 className="text-sm font-black mb-2">{block.title}</h4><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{(block.content?.kpis ?? []).map((item: any, index: number) => <div key={index} className="bg-brand-offwhite border border-brand-border p-3 rounded"><p className="text-[9px] uppercase font-mono text-gray-500">{item.label}</p><p className="text-lg font-black mt-1">{item.value} <span className="text-[10px] font-normal">{item.unit}</span></p></div>)}</div></div>;
  if (block.block_type === 'chart') { const rows = block.content?.rows ?? [], max = Math.max(1, ...rows.map((row: any[]) => Number(row[1]) || 0)); return <div><h4 className="text-sm font-black mb-3">{block.title || 'Chart'}</h4><div className="space-y-2">{rows.map((row: any[], index: number) => <div key={index} className="grid grid-cols-[100px_1fr_55px] gap-2 items-center text-[10px]"><span className="truncate">{row[0]}</span><div className="h-3 bg-brand-offwhite"><div className="h-full bg-brand-forest" style={{ width: `${Math.max(2, Number(row[1]) / max * 100)}%` }} /></div><span className="font-mono text-right">{row[1]}</span></div>)}</div></div>; }
  if (block.block_type === 'table') return <div className="overflow-auto"><h4 className="text-sm font-black mb-2">{block.title}</h4><table className="w-full text-xs border-collapse"><tbody>{(block.content?.rows ?? block.content?.table ?? []).map((row: any, index: number) => { const cells = Array.isArray(row) ? row : [row.name ?? row.label, row.value ?? row.emissionsTco2e]; return <tr key={index} className={index === 0 ? 'bg-brand-offwhite font-bold' : ''}>{cells.map((cell: any, cellIndex: number) => <td key={cellIndex} className="border border-brand-border px-2 py-1.5">{String(cell ?? '')}</td>)}</tr>; })}</tbody></table></div>;
  if (block.block_type === 'image') return block.content?.url ? <figure><img src={block.content.url} alt={block.content.caption || block.title || 'Report visual'} className="max-h-80 w-full object-contain bg-brand-offwhite" /><figcaption className="text-[10px] text-gray-500 mt-1">{block.content.caption}</figcaption></figure> : <div className="h-36 bg-brand-offwhite border border-dashed border-brand-border flex items-center justify-center text-xs text-gray-400"><Image className="w-4 h-4 mr-2" />Add an image URL</div>;
  if (block.block_type === 'spacer') return <div className="h-12 border-y border-dashed border-brand-border" />;
  return null;
}

function BlockEditor({ block, disabled, onChange }: { block: StudioBlock; disabled: boolean; onChange: (content: any) => void }) {
  if (['heading','narrative','callout'].includes(block.block_type)) return <textarea value={block.content?.text ?? ''} disabled={disabled} onChange={(event) => onChange({ ...block.content, text: event.target.value })} className="studio-input min-h-28 resize-y" placeholder="Report content" />;
  if (block.block_type === 'image') return <><input value={block.content?.url ?? ''} disabled={disabled} onChange={(event) => onChange({ ...block.content, url: event.target.value })} className="studio-input" placeholder="Image URL or data URL" /><input value={block.content?.caption ?? ''} disabled={disabled} onChange={(event) => onChange({ ...block.content, caption: event.target.value })} className="studio-input" placeholder="Caption" /></>;
  if (['table','chart','kpi-grid'].includes(block.block_type)) { const value = block.block_type === 'kpi-grid' ? block.content?.kpis : block.content?.rows ?? block.content?.table; return <textarea defaultValue={JSON.stringify(value ?? [], null, 2)} disabled={disabled} onBlur={(event) => { try { const parsed = JSON.parse(event.target.value); onChange(block.block_type === 'kpi-grid' ? { ...block.content, kpis: parsed } : { ...block.content, rows: parsed }); } catch { /* Keep the previous valid structured value. */ } }} className="studio-input min-h-36 font-mono text-[10px]" aria-label={`${block.block_type} data as JSON`} />; }
  return <p className="text-xs text-gray-500">This layout block has no content properties.</p>;
}
