-- Formal Phase 12: Workflow and Collaboration. Apply after 027.
create table if not exists collaboration_tasks(id text primary key,organisation_id text not null references organisations(id) on delete cascade,title text not null,description text not null default '',subject_type text not null default 'general',subject_id text,assignee_id uuid references auth.users(id) on delete set null,created_by uuid references auth.users(id) on delete set null,priority text not null default 'medium' check(priority in ('low','medium','high','critical')),status text not null default 'open' check(status in ('open','in-progress','blocked','completed','cancelled')),due_at timestamptz,completed_at timestamptz,escalated_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists collaboration_comments(id text primary key,organisation_id text not null references organisations(id) on delete cascade,subject_type text not null,subject_id text not null,message text not null,mentions uuid[] not null default '{}',created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),edited_at timestamptz,deleted_at timestamptz);
create table if not exists review_cycles(id text primary key,organisation_id text not null references organisations(id) on delete cascade,subject_type text not null,subject_id text not null,title text not null,reviewer_id uuid references auth.users(id) on delete set null,requested_by uuid references auth.users(id) on delete set null,status text not null default 'requested' check(status in ('requested','in-review','approved','changes-requested','rejected','cancelled')),due_at timestamptz,decision_comment text not null default '',decided_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists evidence_requests(id text primary key,organisation_id text not null references organisations(id) on delete cascade,title text not null,description text not null default '',subject_type text not null,subject_id text,requested_from uuid references auth.users(id) on delete set null,requested_by uuid references auth.users(id) on delete set null,document_id text references documents(id) on delete set null,status text not null default 'open' check(status in ('open','submitted','accepted','changes-requested','cancelled')),due_at timestamptz,response_note text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists collaboration_notifications(id text primary key,organisation_id text not null references organisations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,type text not null,title text not null,body text not null default '',link_view text not null default '',metadata jsonb not null default '{}'::jsonb,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists collaboration_activity_feed(id text primary key,organisation_id text not null references organisations(id) on delete cascade,actor_id uuid references auth.users(id) on delete set null,event_type text not null,subject_type text not null,subject_id text,summary text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists document_approvals(id text primary key,organisation_id text not null references organisations(id) on delete cascade,document_id text not null references documents(id) on delete cascade,reviewer_id uuid references auth.users(id) on delete set null,status text not null default 'requested' check(status in ('requested','approved','changes-requested','rejected')),comment text not null default '',requested_by uuid references auth.users(id) on delete set null,decided_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists collaboration_email_outbox(id text primary key,organisation_id text not null references organisations(id) on delete cascade,recipient_email text not null,template_key text not null,payload jsonb not null default '{}'::jsonb,status text not null default 'queued' check(status in ('queued','sent','failed','cancelled')),attempt_count integer not null default 0,last_error text not null default '',created_at timestamptz not null default now(),sent_at timestamptz);
create index if not exists idx_collab_tasks_org on collaboration_tasks(organisation_id,status,due_at);create index if not exists idx_collab_notifications_user on collaboration_notifications(organisation_id,user_id,created_at desc);create index if not exists idx_collab_feed_org on collaboration_activity_feed(organisation_id,created_at desc);create index if not exists idx_review_cycles_org on review_cycles(organisation_id,status);create index if not exists idx_evidence_requests_org on evidence_requests(organisation_id,status);
drop trigger if exists trg_collaboration_tasks_updated_at on collaboration_tasks;create trigger trg_collaboration_tasks_updated_at before update on collaboration_tasks for each row execute function set_updated_at();drop trigger if exists trg_review_cycles_updated_at on review_cycles;create trigger trg_review_cycles_updated_at before update on review_cycles for each row execute function set_updated_at();drop trigger if exists trg_evidence_requests_updated_at on evidence_requests;create trigger trg_evidence_requests_updated_at before update on evidence_requests for each row execute function set_updated_at();drop trigger if exists trg_document_approvals_updated_at on document_approvals;create trigger trg_document_approvals_updated_at before update on document_approvals for each row execute function set_updated_at();
alter table collaboration_tasks enable row level security;alter table collaboration_comments enable row level security;alter table review_cycles enable row level security;alter table evidence_requests enable row level security;alter table collaboration_notifications enable row level security;alter table collaboration_activity_feed enable row level security;alter table document_approvals enable row level security;alter table collaboration_email_outbox enable row level security;
insert into permissions(id,key,description) values ('perm-collaboration-view','collaboration.view','View tasks, reviews, requests, comments and notifications'),('perm-collaboration-manage','collaboration.manage','Create and manage collaboration workflows'),('perm-collaboration-review','collaboration.review','Act on review and evidence workflows') on conflict(id) do update set key=excluded.key,description=excluded.description;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r cross join permissions p where r.id in ('role-super-admin','role-platform-admin','role-organisation-admin','role-sustainability-manager','role-plant-manager') and p.key in ('collaboration.view','collaboration.manage','collaboration.review') on conflict do nothing;insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r cross join permissions p where r.id in ('role-operator','role-auditor') and p.key in ('collaboration.view','collaboration.review') on conflict do nothing;
insert into entitlements(id,category_id,key,name,description) values ('ent-collaboration-workflows','cat-support','collaboration.workflows','Workflow and Collaboration','Tasks, comments, reviews, evidence requests, notifications and escalations.') on conflict(id) do update set name=excluded.name,description=excluded.description;insert into plan_entitlements(plan_id,entitlement_id) select p.id,e.id from plans p cross join entitlements e where p.id in ('plan-professional','plan-enterprise') and e.key='collaboration.workflows' on conflict do nothing;
