-- Optional launch seed for the dashboard Scope 3 calculator.
-- These coefficients are illustrative screening defaults, not audit-grade factors.
-- Replace them with supplier-specific, physical or authoritative factor data before reporting.

-- The application uses source-specific catalog IDs. Keep these aliases alongside the
-- broader category rows created by migration 031 so factor lineage remains explicit.
insert into carbon_activity_source_catalog (
  id, scope, category, ghg_category, name, description, default_calculation_method,
  allowed_units, evidence_hint, supplier_relevant, status
) values
('s3-01-purchased-goods-services','scope-3','scope3-category-01','Category 1: Purchased goods and services','Purchased goods and services','Cradle-to-gate emissions from purchased materials and services.','supplier-specific','["kg","tonne","INR","USD"]'::jsonb,'Supplier-specific product footprint, EPD, invoice or purchase ledger.',true,'active'),
('s3-02-capital-goods','scope-3','scope3-category-02','Category 2: Capital goods','Capital goods','Cradle-to-gate emissions from purchased capital assets.','spend-factor','["INR","USD","kg","tonne"]'::jsonb,'Asset register, invoice and supplier disclosure.',true,'active'),
('s3-03-fuel-energy-related','scope-3','scope3-category-03','Category 3: Fuel- and energy-related activities','Fuel- and energy-related activities','Upstream fuel and energy emissions outside Scope 1 and Scope 2.','activity-factor','["kWh","MWh","litre","kg","tonne"]'::jsonb,'Energy ledger and upstream factor source.',true,'active'),
('s3-04-upstream-transport','scope-3','scope3-category-04','Category 4: Upstream transportation and distribution','Upstream transportation and distribution','Third-party inbound freight and warehousing.','distance-factor','["tonne-km","vehicle-km","INR","USD"]'::jsonb,'Freight invoice, route and load record.',true,'active'),
('s3-05-waste-operations','scope-3','scope3-category-05','Category 5: Waste generated in operations','Waste generated in operations','Third-party treatment and disposal of operational waste.','activity-factor','["kg","tonne"]'::jsonb,'Waste manifest and treatment route.',true,'active'),
('s3-06-business-travel','scope-3','scope3-category-06','Category 6: Business travel','Business travel','Employee travel in non-owned transport and accommodation.','distance-factor','["passenger-km","room-night","INR","USD"]'::jsonb,'Travel booking and expense record.',true,'active'),
('s3-07-employee-commuting','scope-3','scope3-category-07','Category 7: Employee commuting','Employee commuting','Travel between employee homes and workplaces.','distance-factor','["passenger-km","vehicle-km"]'::jsonb,'Travel survey and attendance data.',true,'active'),
('s3-08-upstream-leased-assets','scope-3','scope3-category-08','Category 8: Upstream leased assets','Upstream leased assets','Operation of leased assets outside Scope 1 and Scope 2.','activity-factor','["kWh","MWh","litre","kg"]'::jsonb,'Lease and utility records.',true,'active'),
('s3-09-downstream-transport','scope-3','scope3-category-09','Category 9: Downstream transportation and distribution','Downstream transportation and distribution','Third-party outbound freight and warehousing.','distance-factor','["tonne-km","vehicle-km","INR","USD"]'::jsonb,'Freight invoice, route and load record.',true,'active'),
('s3-10-processing-sold-products','scope-3','scope3-category-10','Category 10: Processing of sold products','Processing of sold products','Downstream processing of intermediate products.','activity-factor','["kg","tonne","kWh","MWh"]'::jsonb,'Customer process data and product quantity.',true,'active'),
('s3-11-use-sold-products','scope-3','scope3-category-11','Category 11: Use of sold products','Use of sold products','Lifetime customer use emissions from sold products.','activity-factor','["unit","kWh","MWh","litre"]'::jsonb,'Sales volume, lifetime and use profile.',true,'active'),
('s3-12-end-life-sold-products','scope-3','scope3-category-12','Category 12: End-of-life treatment of sold products','End-of-life treatment of sold products','Treatment of products at end of life.','activity-factor','["kg","tonne","unit"]'::jsonb,'Material composition and disposal scenario.',true,'active'),
('s3-13-downstream-leased-assets','scope-3','scope3-category-13','Category 13: Downstream leased assets','Downstream leased assets','Operation of owned assets leased to others.','activity-factor','["kWh","MWh","litre","kg"]'::jsonb,'Lease and tenant utility records.',true,'active'),
('s3-14-franchises','scope-3','scope3-category-14','Category 14: Franchises','Franchises','Operational emissions from franchises.','activity-factor','["kWh","MWh","litre","kg"]'::jsonb,'Franchise activity submissions.',true,'active'),
('s3-15-investments','scope-3','scope3-category-15','Category 15: Investments','Investments','Financed emissions associated with investment and lending portfolios.','supplier-specific','["INR","USD","tCO2e"]'::jsonb,'Investee emissions and attribution data.',true,'active')
on conflict (id) do update set
  category=excluded.category, ghg_category=excluded.ghg_category, name=excluded.name,
  description=excluded.description, default_calculation_method=excluded.default_calculation_method,
  allowed_units=excluded.allowed_units, evidence_hint=excluded.evidence_hint,
  supplier_relevant=excluded.supplier_relevant, status=excluded.status, updated_at=now();

insert into emission_factor_registry (
  id, factor_key, source_type, scope, country, region, source_name, version, publication_year, effective_from,
  factor_value, factor_unit, activity_unit, reference_url, status, factor_source, factor_family, calculation_method,
  geography_level, quality_rating, is_custom, approval_status, organisation_id, source_catalog_id, metadata
) values
('efr-public-s3-01-purchased-goods-services','public-scope3-01-purchased-goods-services','Purchased goods and services','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.5,'kgCO2e/kg','kg','','active','illustrative-screening','scope-3','supplier-specific','global','screening',false,'published',null,'s3-01-purchased-goods-services','{"screeningOnly":true}'::jsonb),
('efr-public-s3-02-capital-goods','public-scope3-02-capital-goods','Capital goods','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.0004,'kgCO2e/INR','INR','','active','illustrative-screening','scope-3','spend-factor','global','screening',false,'published',null,'s3-02-capital-goods','{"screeningOnly":true}'::jsonb),
('efr-public-s3-03-fuel-energy-related','public-scope3-03-fuel-energy-related','Fuel- and energy-related activities','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.12,'kgCO2e/kWh','kWh','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-03-fuel-energy-related','{"screeningOnly":true}'::jsonb),
('efr-public-s3-04-upstream-transport','public-scope3-04-upstream-transport','Upstream transportation and distribution','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.12,'kgCO2e/tonne-km','tonne-km','','active','illustrative-screening','scope-3','distance-factor','global','screening',false,'published',null,'s3-04-upstream-transport','{"screeningOnly":true}'::jsonb),
('efr-public-s3-05-waste-operations','public-scope3-05-waste-operations','Waste generated in operations','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.45,'kgCO2e/kg','kg','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-05-waste-operations','{"screeningOnly":true}'::jsonb),
('efr-public-s3-06-business-travel','public-scope3-06-business-travel','Business travel','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.15,'kgCO2e/passenger-km','passenger-km','','active','illustrative-screening','scope-3','distance-factor','global','screening',false,'published',null,'s3-06-business-travel','{"screeningOnly":true}'::jsonb),
('efr-public-s3-07-employee-commuting','public-scope3-07-employee-commuting','Employee commuting','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.12,'kgCO2e/passenger-km','passenger-km','','active','illustrative-screening','scope-3','distance-factor','global','screening',false,'published',null,'s3-07-employee-commuting','{"screeningOnly":true}'::jsonb),
('efr-public-s3-08-upstream-leased-assets','public-scope3-08-upstream-leased-assets','Upstream leased assets','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.716,'kgCO2e/kWh','kWh','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-08-upstream-leased-assets','{"screeningOnly":true}'::jsonb),
('efr-public-s3-09-downstream-transport','public-scope3-09-downstream-transport','Downstream transportation and distribution','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.12,'kgCO2e/tonne-km','tonne-km','','active','illustrative-screening','scope-3','distance-factor','global','screening',false,'published',null,'s3-09-downstream-transport','{"screeningOnly":true}'::jsonb),
('efr-public-s3-10-processing-sold-products','public-scope3-10-processing-sold-products','Processing of sold products','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.716,'kgCO2e/kWh','kWh','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-10-processing-sold-products','{"screeningOnly":true}'::jsonb),
('efr-public-s3-11-use-sold-products','public-scope3-11-use-sold-products','Use of sold products','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.716,'kgCO2e/kWh','kWh','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-11-use-sold-products','{"screeningOnly":true}'::jsonb),
('efr-public-s3-12-end-life-sold-products','public-scope3-12-end-life-sold-products','End-of-life treatment of sold products','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.45,'kgCO2e/kg','kg','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-12-end-life-sold-products','{"screeningOnly":true}'::jsonb),
('efr-public-s3-13-downstream-leased-assets','public-scope3-13-downstream-leased-assets','Downstream leased assets','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.716,'kgCO2e/kWh','kWh','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-13-downstream-leased-assets','{"screeningOnly":true}'::jsonb),
('efr-public-s3-14-franchises','public-scope3-14-franchises','Franchises','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.716,'kgCO2e/kWh','kWh','','active','illustrative-screening','scope-3','activity-factor','global','screening',false,'published',null,'s3-14-franchises','{"screeningOnly":true}'::jsonb),
('efr-public-s3-15-investments','public-scope3-15-investments','Investments','scope-3','Global','Screening estimate','Balancing Carbon illustrative Scope 3 screening coefficient; replace before reporting','screening-2026.1',2026,'2026-01-01',0.0002,'kgCO2e/INR','INR','','active','illustrative-screening','scope-3','supplier-specific','global','screening',false,'published',null,'s3-15-investments','{"screeningOnly":true}'::jsonb)
on conflict (id) do update set
  factor_value=excluded.factor_value, factor_unit=excluded.factor_unit, activity_unit=excluded.activity_unit,
  source_name=excluded.source_name, version=excluded.version, quality_rating=excluded.quality_rating,
  approval_status=excluded.approval_status, source_catalog_id=excluded.source_catalog_id, metadata=excluded.metadata;
